/**
 * AŞAMA 22 — Hafif OpenAPI 3 özeti (keşif / dokümantasyon).
 */

export function buildOpenApi() {
  return {
    openapi: '3.0.3',
    info: {
      title: 'LİKYA / OlymposPass Platform API',
      version: '1.0.0',
      description: 'CEO paneli Vite middleware API yüzeyi (AŞAMA 1–375)',
    },
    servers: [{ url: '/' }],
    paths: {
      '/api/health': { get: { summary: 'Healthcheck', tags: ['ops'] } },
      '/api/auth/login': { post: { summary: 'Giriş', tags: ['auth'] } },
      '/api/auth/me': { get: { summary: 'Oturum', tags: ['auth'] } },
      '/api/hub/summary': { get: { summary: 'Hub özeti', tags: ['hub'] } },
      '/api/archive': {
        get: { summary: 'Arşiv listesi', tags: ['archive'] },
        post: { summary: 'Arşiv kaydet', tags: ['archive'] },
      },
      '/api/search': { get: { summary: 'HERODOT arama', tags: ['research'] } },
      '/api/whatsapp/send': { post: { summary: 'WhatsApp gönder', tags: ['integrations'] } },
      '/api/mint/demand': { get: { summary: 'MINT talep matrisi', tags: ['integrations'] } },
      '/api/nexus/devices': { get: { summary: 'NEXUS cihazlar', tags: ['nexus'] } },
      '/api/nexus/command': { post: { summary: 'NEXUS komut', tags: ['nexus'] } },
      '/api/pass/admit': { post: { summary: 'Geçiş onayla', tags: ['pass'] } },
      '/api/pass/verify': { post: { summary: 'Geçiş doğrula', tags: ['pass'] } },
      '/api/venues': { get: { summary: 'Tesisler', tags: ['venues'] } },
      '/api/brands': { get: { summary: 'Markalar', tags: ['brands'] } },
      '/api/brands/active': { post: { summary: 'Aktif marka seç', tags: ['brands'] } },
      '/api/guests': { get: { summary: 'Misafir CRM', tags: ['crm'] } },
      '/api/jobs': { get: { summary: 'Görev kuyruğu', tags: ['jobs'] } },
      '/api/playbooks': { get: { summary: 'Playbook şablonları', tags: ['komuta'] } },
      '/api/webhooks': { get: { summary: 'Webhook listesi', tags: ['webhooks'] } },
      '/api/metrics': { get: { summary: 'Metrikler', tags: ['obs'] } },
      '/api/report': { get: { summary: 'Operasyon raporu', tags: ['report'] } },
      '/api/ops/backup': { get: { summary: 'Yedek indir', tags: ['ops'] } },
      '/api/ops/restore': { post: { summary: 'Yedek geri yükle', tags: ['ops'] } },
      '/api/inventory': { get: { summary: 'Stok envanteri', tags: ['inventory'] } },
      '/api/inventory/adjust': { post: { summary: 'Stok hareketi', tags: ['inventory'] } },
      '/api/shifts': {
        get: { summary: 'Vardiya planı', tags: ['shifts'] },
        post: { summary: 'Vardiya oluştur', tags: ['shifts'] },
      },
      '/api/shifts/{id}': {
        patch: { summary: 'Vardiya güncelle', tags: ['shifts'] },
        delete: { summary: 'Vardiya sil (CEO)', tags: ['shifts'] },
      },
      '/api/openapi.json': { get: { summary: 'OpenAPI JSON', tags: ['docs'] } },
      '/api/docs': { get: { summary: 'API docs alias', tags: ['docs'] } },
      '/api/reservations': {
        get: { summary: 'Rezervasyon listesi', tags: ['reservations'] },
        post: { summary: 'Rezervasyon oluştur', tags: ['reservations'] },
      },
      '/api/loyalty': { get: { summary: 'Sadakat hesapları', tags: ['loyalty'] } },
      '/api/loyalty/adjust': { post: { summary: 'Puan hareketi', tags: ['loyalty'] } },
      '/api/incidents': {
        get: { summary: 'Olay panosu', tags: ['incidents'] },
        post: { summary: 'Manuel olay', tags: ['incidents'] },
      },
      '/api/incidents/{id}/ack': { post: { summary: 'Olay onay/çöz', tags: ['incidents'] } },
      '/api/suppliers': { get: { summary: 'Tedarikçiler', tags: ['suppliers'] } },
      '/api/purchase-orders': {
        get: { summary: 'Satınalma siparişleri', tags: ['suppliers'] },
        post: { summary: 'Sipariş aç', tags: ['suppliers'] },
      },
      '/api/feedback': {
        get: { summary: 'NPS / geri bildirim', tags: ['feedback'] },
        post: { summary: 'Skor ekle', tags: ['feedback'] },
      },
      '/api/exports': { get: { summary: 'Export kataloğu', tags: ['exports'] } },
      '/api/exports/{id}': { get: { summary: 'CSV indir', tags: ['exports'] } },
      '/api/consents': {
        get: { summary: 'KVKK onay günlüğü', tags: ['consent'] },
        post: { summary: 'Onay kaydet', tags: ['consent'] },
      },
      '/api/announcements': {
        get: { summary: 'Duyurular', tags: ['announcements'] },
        post: { summary: 'Duyuru yayınla', tags: ['announcements'] },
      },
      '/api/recipes': { get: { summary: 'Reçeteler', tags: ['recipes'] } },
      '/api/recipes/{id}/cook': { post: { summary: 'Reçete pişir → stok düş', tags: ['recipes'] } },
      '/api/checklists': { get: { summary: 'Kontrol listeleri', tags: ['checklists'] } },
      '/api/lost-found': { get: { summary: 'Kayıp eşya', tags: ['lostfound'] } },
      '/api/tips': { get: { summary: 'Bahşiş havuzu', tags: ['tips'] } },
      '/api/audit': { get: { summary: 'Denetim günlüğü', tags: ['audit'] } },
      '/api/maintenance': { get: { summary: 'Bakım ticketları', tags: ['maintenance'] } },
      '/api/brief': { get: { summary: 'Günlük operasyon brifi', tags: ['brief'] } },
      '/api/menu': { get: { summary: 'Menü kataloğu', tags: ['menu'] } },
      '/api/campaigns': { get: { summary: 'Kampanyalar', tags: ['campaigns'] } },
      '/api/i18n': { get: { summary: 'Lokalizasyon notları', tags: ['i18n'] } },
      '/api/coldchain': { get: { summary: 'Soğuk zincir', tags: ['coldchain'] } },
      '/api/handover': { get: { summary: 'Vardiya teslim', tags: ['handover'] } },
      '/api/cash': { get: { summary: 'Kasa', tags: ['cash'] } },
      '/api/assets': { get: { summary: 'Varlık envanteri', tags: ['assets'] } },
      '/api/energy': { get: { summary: 'Enerji sayaçları', tags: ['energy'] } },
      '/api/training': { get: { summary: 'Eğitim / quiz', tags: ['training'] } },
      '/api/readiness': { get: { summary: 'Hazırlık skoru', tags: ['readiness'] } },
      '/api/digest': { get: { summary: 'CEO Digest', tags: ['digest'] } },
      '/api/boardpack': { get: { summary: 'Board Pack', tags: ['boardpack'] } },
      '/api/concierge': { get: { summary: 'Concierge', tags: ['concierge'] } },
      '/api/minibar': { get: { summary: 'Minibar', tags: ['minibar'] } },
      '/api/folio': { get: { summary: 'Misafir Hesap', tags: ['folio'] } },
      '/api/banquet': { get: { summary: 'Banket', tags: ['banquet'] } },
      '/api/tours': { get: { summary: 'Tur Masası', tags: ['tours'] } },
      '/api/marina': { get: { summary: 'Marina', tags: ['marina'] } },
      '/api/hammam': { get: { summary: 'Hamam', tags: ['hammam'] } },
      '/api/towels': { get: { summary: 'Havlu Takibi', tags: ['towels'] } },
      '/api/bands': { get: { summary: 'Günlük Bileklik', tags: ['bands'] } },
      '/api/haccp': { get: { summary: 'HACCP', tags: ['haccp'] } },
      '/api/patrol': { get: { summary: 'Güvenlik Turu', tags: ['patrol'] } },
      '/api/fleet': { get: { summary: 'Araç Filosu', tags: ['fleet'] } },
      '/api/payroll': { get: { summary: 'Bordro Özeti', tags: ['payroll'] } },
      '/api/flash': { get: { summary: 'Flash Rapor', tags: ['flash'] } },
      '/api/warroom': { get: { summary: 'War Room', tags: ['warroom'] } },
      '/api/upsell': { get: { summary: 'Upsell', tags: ['upsell'] } },
      '/api/otareviews': { get: { summary: 'OTA Yorumlar', tags: ['otareviews'] } },
      '/api/groups': { get: { summary: 'Grup Rezervasyon', tags: ['groups'] } },
      '/api/vipnotes': { get: { summary: 'VIP Notları', tags: ['vipnotes'] } },
      '/api/photoshoot': { get: { summary: 'Fotoğraf Çekim', tags: ['photoshoot'] } },
      '/api/dive': { get: { summary: 'Dalış', tags: ['dive'] } },
      '/api/bikerent': { get: { summary: 'Bisiklet', tags: ['bikerent'] } },
      '/api/cinema': { get: { summary: 'Açık Hava Sinema', tags: ['cinema'] } },
      '/api/retail': { get: { summary: 'Butik', tags: ['retail'] } },
      '/api/bakery': { get: { summary: 'Pastane', tags: ['bakery'] } },
      '/api/breakfast': { get: { summary: 'Kahvaltı Slot', tags: ['breakfast'] } },
      '/api/lateout': { get: { summary: 'Late Checkout', tags: ['lateout'] } },
      '/api/amenities': { get: { summary: 'Amenity', tags: ['amenities'] } },
      '/api/nightlog': { get: { summary: 'Gece Log', tags: ['nightlog'] } },
      '/api/nightly': { get: { summary: 'Night Audit', tags: ['nightly'] } },
      '/api/keycards': { get: { summary: 'Oda Kartı', tags: ['keycards'] } },
      '/api/roomstatus': { get: { summary: 'Oda Durumu', tags: ['roomstatus'] } },
      '/api/bedding': { get: { summary: 'Yatak / Extra', tags: ['bedding'] } },
      '/api/wakeups': { get: { summary: 'Wake-up', tags: ['wakeups'] } },
      '/api/parcels': { get: { summary: 'Kargo / Emanet', tags: ['parcels'] } },
      '/api/qrcheckin': { get: { summary: 'QR Check-in', tags: ['qrcheckin'] } },
      '/api/guestapp': { get: { summary: 'Misafir App', tags: ['guestapp'] } },
      '/api/karaoke': { get: { summary: 'Karaoke', tags: ['karaoke'] } },
      '/api/artwall': { get: { summary: 'Sanat Duvarı', tags: ['artwall'] } },
      '/api/florals': { get: { summary: 'Çiçek', tags: ['florals'] } },
      '/api/privatechef': { get: { summary: 'Özel Şef', tags: ['privatechef'] } },
      '/api/mocktails': { get: { summary: 'Mocktail Bar', tags: ['mocktails'] } },
      '/api/promos': { get: { summary: 'Promo Kod', tags: ['promos'] } },
      '/api/dawnservice': { get: { summary: 'Şafak Servisi', tags: ['dawnservice'] } },
      '/api/orbit': { get: { summary: 'Orbit', tags: ['orbit'] } },
      '/api/rosters': { get: { summary: 'Haftalık Roster', tags: ['rosters'] } },
      '/api/overtime': { get: { summary: 'Mesai', tags: ['overtime'] } },
      '/api/uniforms': { get: { summary: 'Üniforma', tags: ['uniforms'] } },
      '/api/healthcards': { get: { summary: 'Sağlık Kartı', tags: ['healthcards'] } },
      '/api/visitors': { get: { summary: 'Ziyaretçi', tags: ['visitors'] } },
      '/api/cctvlog': { get: { summary: 'CCTV Log', tags: ['cctvlog'] } },
      '/api/firedrill': { get: { summary: 'Yangın Tatbikat', tags: ['firedrill'] } },
      '/api/insurance': { get: { summary: 'Sigorta', tags: ['insurance'] } },
      '/api/invoices': { get: { summary: 'Fatura', tags: ['invoices'] } },
      '/api/taxpack': { get: { summary: 'Vergi Paketi', tags: ['taxpack'] } },
      '/api/forecast': { get: { summary: 'Gelir Forecast', tags: ['forecast'] } },
      '/api/capex': { get: { summary: 'CAPEX', tags: ['capex'] } },
      '/api/licenses': { get: { summary: 'Ruhsat', tags: ['licenses'] } },
      '/api/slabreaches': { get: { summary: 'SLA İhlal', tags: ['slabreaches'] } },
      '/api/apex': { get: { summary: 'Apex', tags: ['apex'] } },
      '/api/extlinks': { get: { summary: 'Entegrasyonlar', tags: ['extlinks'] } },
      '/api/apikeys': { get: { summary: 'API Anahtar', tags: ['apikeys'] } },
      '/api/backupsched': { get: { summary: 'Yedek Zamanla', tags: ['backupsched'] } },
      '/api/sysalerts': { get: { summary: 'Sistem Alarm', tags: ['sysalerts'] } },
      '/api/bugtracker': { get: { summary: 'Bug Tracker', tags: ['bugtracker'] } },
      '/api/releasenotes': { get: { summary: 'Release Notes', tags: ['releasenotes'] } },
      '/api/runbooks': { get: { summary: 'Runbook', tags: ['runbooks'] } },
      '/api/biometrics': { get: { summary: 'Biyometrik', tags: ['biometrics'] } },
      '/api/secretsrot': { get: { summary: 'Secret Rotation', tags: ['secretsrot'] } },
      '/api/dnscheck': { get: { summary: 'DNS Check', tags: ['dnscheck'] } },
      '/api/mailqueue': { get: { summary: 'Mail Kuyruk', tags: ['mailqueue'] } },
      '/api/smsqueue': { get: { summary: 'SMS Kuyruk', tags: ['smsqueue'] } },
      '/api/alertrules': { get: { summary: 'Alert Kuralları', tags: ['alertrules'] } },
      '/api/edgecache': { get: { summary: 'Edge Cache', tags: ['edgecache'] } },
      '/api/pyramid': { get: { summary: 'Pyramid', tags: ['pyramid'] } },
      '/api/signage': { get: { summary: 'Dijital Tabela', tags: ['signage'] } },
      '/api/wayfind': { get: { summary: 'Wayfinding', tags: ['wayfind'] } },
      '/api/beaconmap': { get: { summary: 'Beacon Harita', tags: ['beaconmap'] } },
      '/api/iotgates': { get: { summary: 'IoT Kapı', tags: ['iotgates'] } },
      '/api/powerops': { get: { summary: 'Güç Ops', tags: ['powerops'] } },
      '/api/waterops': { get: { summary: 'Su Ops', tags: ['waterops'] } },
      '/api/greenops': { get: { summary: 'Yeşil Ops', tags: ['greenops'] } },
      '/api/pestctrl': { get: { summary: 'Haşere', tags: ['pestctrl'] } },
      '/api/chemlog': { get: { summary: 'Kimyasal Log', tags: ['chemlog'] } },
      '/api/poolops': { get: { summary: 'Havuz Ops', tags: ['poolops'] } },
      '/api/saunaops': { get: { summary: 'Sauna', tags: ['saunaops'] } },
      '/api/steamops': { get: { summary: 'Steam', tags: ['steamops'] } },
      '/api/icebath': { get: { summary: 'Buz Banyo', tags: ['icebath'] } },
      '/api/recovslots': { get: { summary: 'Recovery Slot', tags: ['recovslots'] } },
      '/api/signalhub': { get: { summary: 'Signal Hub', tags: ['signalhub'] } },
      '/api/helipad': { get: { summary: 'Helipad', tags: ['helipad'] } },
      '/api/jetski': { get: { summary: 'Jet Ski', tags: ['jetski'] } },
      '/api/yacht': { get: { summary: 'Yat Charter', tags: ['yacht'] } },
      '/api/surfschool': { get: { summary: 'Surf School', tags: ['surfschool'] } },
      '/api/paddle': { get: { summary: 'Paddle', tags: ['paddle'] } },
      '/api/climwall': { get: { summary: 'Tırmanma', tags: ['climwall'] } },
      '/api/escaperoom': { get: { summary: 'Escape Room', tags: ['escaperoom'] } },
      '/api/arcade': { get: { summary: 'Arcade', tags: ['arcade'] } },
      '/api/bowling': { get: { summary: 'Bowling', tags: ['bowling'] } },
      '/api/billiards': { get: { summary: 'Bilardo', tags: ['billiards'] } },
      '/api/pokertable': { get: { summary: 'Poker', tags: ['pokertable'] } },
      '/api/trivia': { get: { summary: 'Trivia', tags: ['trivia'] } },
      '/api/djbooth': { get: { summary: 'DJ Booth', tags: ['djbooth'] } },
      '/api/soundcheck': { get: { summary: 'Soundcheck', tags: ['soundcheck'] } },
      '/api/skyline': { get: { summary: 'Skyline', tags: ['skyline'] } },
      '/api/crowddens': { get: { summary: 'Yoğunluk', tags: ['crowddens'] } },
      '/api/queuetimes': { get: { summary: 'Kuyruk Süresi', tags: ['queuetimes'] } },
      '/api/lostchild': { get: { summary: 'Kayıp Çocuk', tags: ['lostchild'] } },
      '/api/firstaid': { get: { summary: 'İlk Yardım', tags: ['firstaid'] } },
      '/api/aedcheck': { get: { summary: 'AED Kontrol', tags: ['aedcheck'] } },
      '/api/evacdrill': { get: { summary: 'Tahliye Tatbikat', tags: ['evacdrill'] } },
      '/api/crowdctrl': { get: { summary: 'Kalabalık Kontrol', tags: ['crowdctrl'] } },
      '/api/radiolog': { get: { summary: 'Telsiz Log', tags: ['radiolog'] } },
      '/api/gatequeue': { get: { summary: 'Gate Kuyruk', tags: ['gatequeue'] } },
      '/api/wristscan': { get: { summary: 'Bileklik Scan', tags: ['wristscan'] } },
      '/api/facepass': { get: { summary: 'Face Pass', tags: ['facepass'] } },
      '/api/bagcheck': { get: { summary: 'Çanta Kontrol', tags: ['bagcheck'] } },
      '/api/metaldet': { get: { summary: 'Metal Dedektör', tags: ['metaldet'] } },
      '/api/watchlist': { get: { summary: 'İzleme Listesi', tags: ['watchlist'] } },
      '/api/sentinel': { get: { summary: 'Sentinel', tags: ['sentinel'] } },
      '/api/menuboard': { get: { summary: 'Menü Board', tags: ['menuboard'] } },
      '/api/allergenalert': { get: { summary: 'Alerjen Alarm', tags: ['allergenalert'] } },
      '/api/tempprobe': { get: { summary: 'Sıcaklık Probe', tags: ['tempprobe'] } },
      '/api/prepqueue': { get: { summary: 'Prep Kuyruk', tags: ['prepqueue'] } },
      '/api/voidlog': { get: { summary: 'Void Log', tags: ['voidlog'] } },
      '/api/comps': { get: { summary: 'Comp', tags: ['comps'] } },
      '/api/splitbill': { get: { summary: 'Hesap Böl', tags: ['splitbill'] } },
      '/api/tabopen': { get: { summary: 'Açık Tab', tags: ['tabopen'] } },
      '/api/corkage': { get: { summary: 'Corkage', tags: ['corkage'] } },
      '/api/sommelier': { get: { summary: 'Sommelier', tags: ['sommelier'] } },
      '/api/chefnote': { get: { summary: 'Şef Notu', tags: ['chefnote'] } },
      '/api/passticket': { get: { summary: 'Pass Ticket', tags: ['passticket'] } },
      '/api/zoneheat': { get: { summary: 'Zone Heat', tags: ['zoneheat'] } },
      '/api/revpulse': { get: { summary: 'Rev Pulse', tags: ['revpulse'] } },
      '/api/horizon': { get: { summary: 'Horizon', tags: ['horizon'] } },
      '/api/stayext': { get: { summary: 'Konaklama Uzat', tags: ['stayext'] } },
      '/api/roommove': { get: { summary: 'Oda Taşıma', tags: ['roommove'] } },
      '/api/earlyin': { get: { summary: 'Erken Check-in', tags: ['earlyin'] } },
      '/api/luggage': { get: { summary: 'Bagaj', tags: ['luggage'] } },
      '/api/turndown': { get: { summary: 'Turndown', tags: ['turndown'] } },
      '/api/pillowmenu': { get: { summary: 'Yastık Menü', tags: ['pillowmenu'] } },
      '/api/scenting': { get: { summary: 'Oda Kokusu', tags: ['scenting'] } },
      '/api/dndflags': { get: { summary: 'DND / MUR', tags: ['dndflags'] } },
      '/api/bathstock': { get: { summary: 'Bornoz Stok', tags: ['bathstock'] } },
      '/api/ironreq': { get: { summary: 'Ütü Talebi', tags: ['ironreq'] } },
      '/api/pressing': { get: { summary: 'Pressing', tags: ['pressing'] } },
      '/api/shoeshine': { get: { summary: 'Ayakkabı Boya', tags: ['shoeshine'] } },
      '/api/babycot': { get: { summary: 'Bebek Karyola', tags: ['babycot'] } },
      '/api/petstay': { get: { summary: 'Pet Stay', tags: ['petstay'] } },
      '/api/meridian': { get: { summary: 'Meridian', tags: ['meridian'] } },
      '/api/arbill': { get: { summary: 'AR Fatura', tags: ['arbill'] } },
      '/api/apbill': { get: { summary: 'AP Ödeme', tags: ['apbill'] } },
      '/api/bankrec': { get: { summary: 'Banka Mutabakat', tags: ['bankrec'] } },
      '/api/fxrates': { get: { summary: 'Döviz Kur', tags: ['fxrates'] } },
      '/api/tipout': { get: { summary: 'Tip Out', tags: ['tipout'] } },
      '/api/deposit': { get: { summary: 'Depozito', tags: ['deposit'] } },
      '/api/refunds': { get: { summary: 'İade', tags: ['refunds'] } },
      '/api/chargeback': { get: { summary: 'Chargeback', tags: ['chargeback'] } },
      '/api/giftred': { get: { summary: 'Hediye Kullanım', tags: ['giftred'] } },
      '/api/memberbill': { get: { summary: 'Üyelik Fatura', tags: ['memberbill'] } },
      '/api/rateplan': { get: { summary: 'Rate Plan', tags: ['rateplan'] } },
      '/api/channelmgr': { get: { summary: 'Channel Manager', tags: ['channelmgr'] } },
      '/api/overbook': { get: { summary: 'Overbooking', tags: ['overbook'] } },
      '/api/yieldrule': { get: { summary: 'Yield Kural', tags: ['yieldrule'] } },
      '/api/ledger': { get: { summary: 'Ledger', tags: ['ledger'] } },
      '/api/onboarding': { get: { summary: 'Onboarding', tags: ['onboarding'] } },
      '/api/offboarding': { get: { summary: 'Offboarding', tags: ['offboarding'] } },
      '/api/interviews': { get: { summary: 'Mülakat', tags: ['interviews'] } },
      '/api/certifications': { get: { summary: 'Sertifika', tags: ['certifications'] } },
      '/api/langskill': { get: { summary: 'Dil Yetkinlik', tags: ['langskill'] } },
      '/api/shiftswap': { get: { summary: 'Vardiya Takas', tags: ['shiftswap'] } },
      '/api/leaverequest': { get: { summary: 'İzin Talebi', tags: ['leaverequest'] } },
      '/api/attendance': { get: { summary: 'Yoklama', tags: ['attendance'] } },
      '/api/performance': { get: { summary: 'Performans', tags: ['performance'] } },
      '/api/recognition': { get: { summary: 'Ödül', tags: ['recognition'] } },
      '/api/handbook': { get: { summary: 'El Kitabı', tags: ['handbook'] } },
      '/api/safetybrief': { get: { summary: 'İSG Brifi', tags: ['safetybrief'] } },
      '/api/nearmiss': { get: { summary: 'Near Miss', tags: ['nearmiss'] } },
      '/api/whistle': { get: { summary: 'Bildirim Hattı', tags: ['whistle'] } },
      '/api/peoplehub': { get: { summary: 'People Hub', tags: ['peoplehub'] } },
      '/api/carbonlog': { get: { summary: 'Karbon Log', tags: ['carbonlog'] } },
      '/api/wateraudit': { get: { summary: 'Su Denetim', tags: ['wateraudit'] } },
      '/api/airquality': { get: { summary: 'Hava Kalite', tags: ['airquality'] } },
      '/api/solarops': { get: { summary: 'Güneş Enerji', tags: ['solarops'] } },
      '/api/biodiversity': { get: { summary: 'Biyoçeşitlilik', tags: ['biodiversity'] } },
      '/api/recycling': { get: { summary: 'Geri Dönüşüm', tags: ['recycling'] } },
      '/api/greencert': { get: { summary: 'Yeşil Sertifika', tags: ['greencert'] } },
      '/api/auditfind': { get: { summary: 'Denetim Bulgu', tags: ['auditfind'] } },
      '/api/policyack': { get: { summary: 'Politika Onay', tags: ['policyack'] } },
      '/api/dataprotect': { get: { summary: 'Veri Koruma', tags: ['dataprotect'] } },
      '/api/retention': { get: { summary: 'Saklama Politikası', tags: ['retention'] } },
      '/api/accessreview': { get: { summary: 'Erişim Gözden Geçir', tags: ['accessreview'] } },
      '/api/vendorrisk': { get: { summary: 'Tedarik Risk', tags: ['vendorrisk'] } },
      '/api/legalhold': { get: { summary: 'Legal Hold', tags: ['legalhold'] } },
      '/api/ecosphere': { get: { summary: 'Ecosphere', tags: ['ecosphere'] } },
      '/api/presskit': { get: { summary: 'Basın Kiti', tags: ['presskit'] } },
      '/api/influencer': { get: { summary: 'Influencer', tags: ['influencer'] } },
      '/api/ugcmod': { get: { summary: 'UGC Moderasyon', tags: ['ugcmod'] } },
      '/api/seoaudit': { get: { summary: 'SEO Denetim', tags: ['seoaudit'] } },
      '/api/adspend': { get: { summary: 'Reklam Harcama', tags: ['adspend'] } },
      '/api/brandguard': { get: { summary: 'Marka Koruma', tags: ['brandguard'] } },
      '/api/storyboard': { get: { summary: 'Storyboard', tags: ['storyboard'] } },
      '/api/livestream': { get: { summary: 'Canlı Yayın', tags: ['livestream'] } },
      '/api/podcastshow': { get: { summary: 'Podcast', tags: ['podcastshow'] } },
      '/api/newsletter': { get: { summary: 'Bülten', tags: ['newsletter'] } },
      '/api/tagmap': { get: { summary: 'Hashtag Harita', tags: ['tagmap'] } },
      '/api/socialinbox': { get: { summary: 'Sosyal Inbox', tags: ['socialinbox'] } },
      '/api/mediaembargo': { get: { summary: 'Embargo', tags: ['mediaembargo'] } },
      '/api/creativereq': { get: { summary: 'Kreatif Talep', tags: ['creativereq'] } },
      '/api/brandpulse': { get: { summary: 'Brand Pulse', tags: ['brandpulse'] } },
      '/api/modelops': { get: { summary: 'Model Ops', tags: ['modelops'] } },
      '/api/promptlib': { get: { summary: 'Prompt Lib', tags: ['promptlib'] } },
      '/api/agenteval': { get: { summary: 'Ajan Eval', tags: ['agenteval'] } },
      '/api/tokenbudget': { get: { summary: 'Token Bütçe', tags: ['tokenbudget'] } },
      '/api/ragindex': { get: { summary: 'RAG Index', tags: ['ragindex'] } },
      '/api/toolpermit': { get: { summary: 'Tool İzin', tags: ['toolpermit'] } },
      '/api/sandboxrun': { get: { summary: 'Sandbox Run', tags: ['sandboxrun'] } },
      '/api/hallucheck': { get: { summary: 'Hallucination Check', tags: ['hallucheck'] } },
      '/api/datasetcur': { get: { summary: 'Dataset Kürasyon', tags: ['datasetcur'] } },
      '/api/redteam': { get: { summary: 'Red Team', tags: ['redteam'] } },
      '/api/slaagent': { get: { summary: 'Ajan SLA', tags: ['slaagent'] } },
      '/api/costguard': { get: { summary: 'AI Cost Guard', tags: ['costguard'] } },
      '/api/latencylog': { get: { summary: 'Latency Log', tags: ['latencylog'] } },
      '/api/driftmonitor': { get: { summary: 'Drift Monitor', tags: ['driftmonitor'] } },
      '/api/cognisphere': { get: { summary: 'Cognisphere', tags: ['cognisphere'] } },
      '/api/posbridge': { get: { summary: 'POS Bridge', tags: ['posbridge'] } },
      '/api/dynamint': { get: { summary: 'MINT Fiyat Push', tags: ['dynamint'] } },
      '/api/couriertrack': { get: { summary: 'Kurye Takip', tags: ['couriertrack'] } },
      '/api/autocheckout': { get: { summary: 'Otonom Checkout', tags: ['autocheckout'] } },
      '/api/loyaltyburn': { get: { summary: 'Sadakat Harcama', tags: ['loyaltyburn'] } },
      '/api/treatoffer': { get: { summary: 'İkram Teklifi', tags: ['treatoffer'] } },
      '/api/omnimarket': { get: { summary: 'Omni Market', tags: ['omnimarket'] } },
      '/api/clickcollect': { get: { summary: 'Click & Collect', tags: ['clickcollect'] } },
      '/api/lastmile': { get: { summary: 'Last Mile', tags: ['lastmile'] } },
      '/api/invsync': { get: { summary: 'Stok Senkron', tags: ['invsync'] } },
      '/api/pricepush': { get: { summary: 'Fiyat Push', tags: ['pricepush'] } },
      '/api/qrpay': { get: { summary: 'QR Pay', tags: ['qrpay'] } },
      '/api/courierpool': { get: { summary: 'Kurye Havuzu', tags: ['courierpool'] } },
      '/api/giftrelay': { get: { summary: 'Hediye Relay', tags: ['giftrelay'] } },
      '/api/vanguard': { get: { summary: 'Vanguard · Nexus Prime', tags: ['vanguard'] } },
      '/api/edgegate': { get: { summary: 'Edge Gate', tags: ['edgegate'] } },
      '/api/meshlink': { get: { summary: 'Mesh Link', tags: ['meshlink'] } },
      '/api/radiomesh': { get: { summary: 'Radio Mesh', tags: ['radiomesh'] } },
      '/api/sensorfuse': { get: { summary: 'Sensor Fuse', tags: ['sensorfuse'] } },
      '/api/otafirm': { get: { summary: 'OTA Firmware', tags: ['otafirm'] } },
      '/api/devinventory': { get: { summary: 'Cihaz Envanter', tags: ['devinventory'] } },
      '/api/powerbudget': { get: { summary: 'Güç Bütçe', tags: ['powerbudget'] } },
      '/api/backhaul': { get: { summary: 'Backhaul', tags: ['backhaul'] } },
      '/api/edgecache2': { get: { summary: 'Edge Store', tags: ['edgecache2'] } },
      '/api/syncrepl': { get: { summary: 'Sync Replica', tags: ['syncrepl'] } },
      '/api/failover': { get: { summary: 'Failover', tags: ['failover'] } },
      '/api/telemetry': { get: { summary: 'Telemetry', tags: ['telemetry'] } },
      '/api/netslice': { get: { summary: 'Net Slice', tags: ['netslice'] } },
      '/api/satlink': { get: { summary: 'Sat Link', tags: ['satlink'] } },
      '/api/lattice': { get: { summary: 'Lattice', tags: ['lattice'] } },
      '/api/guesttwin': { get: { summary: 'Guest Twin', tags: ['guesttwin'] } },
      '/api/prefgraph': { get: { summary: 'Tercih Grafı', tags: ['prefgraph'] } },
      '/api/intentscore': { get: { summary: 'Niyet Skoru', tags: ['intentscore'] } },
      '/api/nextbest': { get: { summary: 'Next Best Action', tags: ['nextbest'] } },
      '/api/journeymap': { get: { summary: 'Yolculuk Haritası', tags: ['journeymap'] } },
      '/api/microseg': { get: { summary: 'Mikro Segment', tags: ['microseg'] } },
      '/api/offerlab': { get: { summary: 'Offer Lab', tags: ['offerlab'] } },
      '/api/consentgraph': { get: { summary: 'Consent Graph', tags: ['consentgraph'] } },
      '/api/emotionpulse': { get: { summary: 'Duygu Nabız', tags: ['emotionpulse'] } },
      '/api/servicememory': { get: { summary: 'Servis Hafızası', tags: ['servicememory'] } },
      '/api/recoverypath': { get: { summary: 'Recovery Path', tags: ['recoverypath'] } },
      '/api/lifetimeval': { get: { summary: 'LTV', tags: ['lifetimeval'] } },
      '/api/churnrisk': { get: { summary: 'Churn Risk', tags: ['churnrisk'] } },
      '/api/wowmoment': { get: { summary: 'Wow Moment', tags: ['wowmoment'] } },
      '/api/mirror': { get: { summary: 'Mirror', tags: ['mirror'] } },
      '/api/incidentbus': { get: { summary: 'Incident Bus', tags: ['incidentbus'] } },
      '/api/playtrigger': { get: { summary: 'Play Trigger', tags: ['playtrigger'] } },
      '/api/escalation': { get: { summary: 'Escalation', tags: ['escalation'] } },
      '/api/warroomseat': { get: { summary: 'War Room Seat', tags: ['warroomseat'] } },
      '/api/decisionlog': { get: { summary: 'Decision Log', tags: ['decisionlog'] } },
      '/api/slotrack': { get: { summary: 'SLO Track', tags: ['slotrack'] } },
      '/api/errorbudget': { get: { summary: 'Error Budget', tags: ['errorbudget'] } },
      '/api/changewindow': { get: { summary: 'Change Window', tags: ['changewindow'] } },
      '/api/blameless': { get: { summary: 'Blameless Review', tags: ['blameless'] } },
      '/api/pagerduty': { get: { summary: 'On-Call', tags: ['pagerduty'] } },
      '/api/statuspage': { get: { summary: 'Status Page', tags: ['statuspage'] } },
      '/api/runbooklink': { get: { summary: 'Runbook Link', tags: ['runbooklink'] } },
      '/api/commsbridge': { get: { summary: 'Comms Bridge', tags: ['commsbridge'] } },
      '/api/afteraction': { get: { summary: 'After Action', tags: ['afteraction'] } },
      '/api/keystone': { get: { summary: 'Keystone', tags: ['keystone'] } },
      '/api/mysteryshop': { get: { summary: 'Gizli Müşteri', tags: ['mysteryshop'] } },
      '/api/partners': { get: { summary: 'Partner Oteller', tags: ['partners'] } },
      '/api/shuttle': { get: { summary: 'Shuttle Saatleri', tags: ['shuttle'] } },
      '/api/lounge': { get: { summary: 'Lounge Log', tags: ['lounge'] } },
      '/api/winecellar': { get: { summary: 'Şarap Mahzeni', tags: ['winecellar'] } },
      '/api/allergens': { get: { summary: 'Alerjen Matrisi', tags: ['allergens'] } },
      '/api/sustain': { get: { summary: 'Sürdürülebilirlik', tags: ['sustain'] } },
      '/api/mediakit': { get: { summary: 'Medya Kiti', tags: ['mediakit'] } },
      '/api/meetingrooms': { get: { summary: 'Toplantı Odaları', tags: ['meetingrooms'] } },
      '/api/badgeprint': { get: { summary: 'Kart Baskı', tags: ['badgeprint'] } },
      '/api/transfers': { get: { summary: 'Transfer Masası', tags: ['transfers'] } },
      '/api/beachbeds': { get: { summary: 'Şezlong', tags: ['beachbeds'] } },
      '/api/kidsclub': { get: { summary: 'Kids Club', tags: ['kidsclub'] } },
      '/api/lockers': { get: { summary: 'Dolap Kiralama', tags: ['lockers'] } },
      '/api/emergency': { get: { summary: 'Acil Rehber', tags: ['emergency'] } },
      '/api/kds': { get: { summary: 'KDS', tags: ['kds'] } },
      '/api/passstock': { get: { summary: 'Pass Stok', tags: ['passstock'] } },
      '/api/contracts': { get: { summary: 'Sözleşmeler', tags: ['contracts'] } },
      '/api/budget': { get: { summary: 'Bütçe', tags: ['budget'] } },
      '/api/pulse': { get: { summary: 'Ekip Nabız', tags: ['pulse'] } },
      '/api/content': { get: { summary: 'İçerik Kuyruğu', tags: ['content'] } },
      '/api/wifi': { get: { summary: 'WiFi Kupon', tags: ['wifi'] } },
      '/api/laundry': { get: { summary: 'Çamaşırhane', tags: ['laundry'] } },
      '/api/cleaning': { get: { summary: 'Temizlik', tags: ['cleaning'] } },
      '/api/delivery': { get: { summary: 'Paket Servis', tags: ['delivery'] } },
      '/api/giftcards': { get: { summary: 'Hediye Kartları', tags: ['giftcards'] } },
      '/api/eventcal': { get: { summary: 'Etkinlikler', tags: ['eventcal'] } },
      '/api/spa': { get: { summary: 'Spa / Wellness', tags: ['spa'] } },
      '/api/weather': { get: { summary: 'Hava brifi', tags: ['weather'] } },
      '/api/hours': { get: { summary: 'Çalışma saatleri', tags: ['hours'] } },
      '/api/kudos': { get: { summary: 'Takdir', tags: ['kudos'] } },
      '/api/complaints': { get: { summary: 'Şikayetler', tags: ['complaints'] } },
      '/api/waitlist': { get: { summary: 'Bekleme listesi', tags: ['waitlist'] } },
      '/api/seating': { get: { summary: 'Oturma planı', tags: ['seating'] } },
      '/api/waste': { get: { summary: 'Fire günlüğü', tags: ['waste'] } },
      '/api/vendor-scores': { get: { summary: 'Tedarikçi skor', tags: ['vendors'] } },
      '/api/documents': { get: { summary: 'Belge kasası', tags: ['documents'] } },
      '/api/music': { get: { summary: 'Müzik istekleri', tags: ['music'] } },
      '/api/valet': { get: { summary: 'Vale fişleri', tags: ['valet'] } },
      '/api/notifications': { get: { summary: 'Bildirimler', tags: ['notify'] } },
      '/api/events': { get: { summary: 'SSE olay akışı', tags: ['realtime'] } },
      '/api/settings': { get: { summary: 'Ayarlar', tags: ['settings'] } },
    },
  };
}
