/**
 * AŞAMA 22 — Hafif OpenAPI 3 özeti (keşif / dokümantasyon).
 */

export function buildOpenApi() {
  return {
    openapi: '3.0.3',
    info: {
      title: 'LİKYA / OlymposPass Platform API',
      version: '1.0.0',
      description: 'CEO paneli Vite middleware API yüzeyi (AŞAMA 1–90)',
    },
    servers: [{ url: '/' }],
    paths: {
      '/api/health': { get: { summary: 'Healthcheck', tags: ['ops'] } },
      '/api/auth/login': { post: { summary: 'Giriş', tags: ['auth'] } },
      '/api/auth/me': { get: { summary: 'Oturum', tags: ['auth'] } },
      '/api/hub/summary': { get: { summary: 'Hub özeti', tags: ['hub'] } },
      '/api/archive': {
        get: { summary: 'Arşiv listesi', tags: ['archive'] },
        post: { summary: 'Arşiv kaydet', tags: ['archive'] },
      },
      '/api/search': { get: { summary: 'HERODOT arama', tags: ['research'] } },
      '/api/whatsapp/send': { post: { summary: 'WhatsApp gönder', tags: ['integrations'] } },
      '/api/mint/demand': { get: { summary: 'MINT talep matrisi', tags: ['integrations'] } },
      '/api/nexus/devices': { get: { summary: 'NEXUS cihazlar', tags: ['nexus'] } },
      '/api/nexus/command': { post: { summary: 'NEXUS komut', tags: ['nexus'] } },
      '/api/pass/admit': { post: { summary: 'Geçiş onayla', tags: ['pass'] } },
      '/api/pass/verify': { post: { summary: 'Geçiş doğrula', tags: ['pass'] } },
      '/api/venues': { get: { summary: 'Tesisler', tags: ['venues'] } },
      '/api/brands': { get: { summary: 'Markalar', tags: ['brands'] } },
      '/api/brands/active': { post: { summary: 'Aktif marka seç', tags: ['brands'] } },
      '/api/guests': { get: { summary: 'Misafir CRM', tags: ['crm'] } },
      '/api/jobs': { get: { summary: 'Görev kuyruğu', tags: ['jobs'] } },
      '/api/playbooks': { get: { summary: 'Playbook şablonları', tags: ['komuta'] } },
      '/api/webhooks': { get: { summary: 'Webhook listesi', tags: ['webhooks'] } },
      '/api/metrics': { get: { summary: 'Metrikler', tags: ['obs'] } },
      '/api/report': { get: { summary: 'Operasyon raporu', tags: ['report'] } },
      '/api/ops/backup': { get: { summary: 'Yedek indir', tags: ['ops'] } },
      '/api/ops/restore': { post: { summary: 'Yedek geri yükle', tags: ['ops'] } },
      '/api/inventory': { get: { summary: 'Stok envanteri', tags: ['inventory'] } },
      '/api/inventory/adjust': { post: { summary: 'Stok hareketi', tags: ['inventory'] } },
      '/api/shifts': {
        get: { summary: 'Vardiya planı', tags: ['shifts'] },
        post: { summary: 'Vardiya oluştur', tags: ['shifts'] },
      },
      '/api/shifts/{id}': {
        patch: { summary: 'Vardiya güncelle', tags: ['shifts'] },
        delete: { summary: 'Vardiya sil (CEO)', tags: ['shifts'] },
      },
      '/api/openapi.json': { get: { summary: 'OpenAPI JSON', tags: ['docs'] } },
      '/api/docs': { get: { summary: 'API docs alias', tags: ['docs'] } },
      '/api/reservations': {
        get: { summary: 'Rezervasyon listesi', tags: ['reservations'] },
        post: { summary: 'Rezervasyon oluştur', tags: ['reservations'] },
      },
      '/api/loyalty': { get: { summary: 'Sadakat hesapları', tags: ['loyalty'] } },
      '/api/loyalty/adjust': { post: { summary: 'Puan hareketi', tags: ['loyalty'] } },
      '/api/incidents': {
        get: { summary: 'Olay panosu', tags: ['incidents'] },
        post: { summary: 'Manuel olay', tags: ['incidents'] },
      },
      '/api/incidents/{id}/ack': { post: { summary: 'Olay onay/çöz', tags: ['incidents'] } },
      '/api/suppliers': { get: { summary: 'Tedarikçiler', tags: ['suppliers'] } },
      '/api/purchase-orders': {
        get: { summary: 'Satınalma siparişleri', tags: ['suppliers'] },
        post: { summary: 'Sipariş aç', tags: ['suppliers'] },
      },
      '/api/feedback': {
        get: { summary: 'NPS / geri bildirim', tags: ['feedback'] },
        post: { summary: 'Skor ekle', tags: ['feedback'] },
      },
      '/api/exports': { get: { summary: 'Export kataloğu', tags: ['exports'] } },
      '/api/exports/{id}': { get: { summary: 'CSV indir', tags: ['exports'] } },
      '/api/consents': {
        get: { summary: 'KVKK onay günlüğü', tags: ['consent'] },
        post: { summary: 'Onay kaydet', tags: ['consent'] },
      },
      '/api/announcements': {
        get: { summary: 'Duyurular', tags: ['announcements'] },
        post: { summary: 'Duyuru yayınla', tags: ['announcements'] },
      },
      '/api/recipes': { get: { summary: 'Reçeteler', tags: ['recipes'] } },
      '/api/recipes/{id}/cook': { post: { summary: 'Reçete pişir → stok düş', tags: ['recipes'] } },
      '/api/checklists': { get: { summary: 'Kontrol listeleri', tags: ['checklists'] } },
      '/api/lost-found': { get: { summary: 'Kayıp eşya', tags: ['lostfound'] } },
      '/api/tips': { get: { summary: 'Bahşiş havuzu', tags: ['tips'] } },
      '/api/audit': { get: { summary: 'Denetim günlüğü', tags: ['audit'] } },
      '/api/maintenance': { get: { summary: 'Bakım ticketları', tags: ['maintenance'] } },
      '/api/brief': { get: { summary: 'Günlük operasyon brifi', tags: ['brief'] } },
      '/api/menu': { get: { summary: 'Menü kataloğu', tags: ['menu'] } },
      '/api/campaigns': { get: { summary: 'Kampanyalar', tags: ['campaigns'] } },
      '/api/i18n': { get: { summary: 'Lokalizasyon notları', tags: ['i18n'] } },
      '/api/coldchain': { get: { summary: 'Soğuk zincir', tags: ['coldchain'] } },
      '/api/handover': { get: { summary: 'Vardiya teslim', tags: ['handover'] } },
      '/api/cash': { get: { summary: 'Kasa', tags: ['cash'] } },
      '/api/assets': { get: { summary: 'Varlık envanteri', tags: ['assets'] } },
      '/api/energy': { get: { summary: 'Enerji sayaçları', tags: ['energy'] } },
      '/api/training': { get: { summary: 'Eğitim / quiz', tags: ['training'] } },
      '/api/readiness': { get: { summary: 'Hazırlık skoru', tags: ['readiness'] } },
      '/api/digest': { get: { summary: 'CEO Digest', tags: ['digest'] } },
      '/api/boardpack': { get: { summary: 'Board Pack', tags: ['boardpack'] } },
      '/api/mysteryshop': { get: { summary: 'Gizli Müşteri', tags: ['mysteryshop'] } },
      '/api/partners': { get: { summary: 'Partner Oteller', tags: ['partners'] } },
      '/api/shuttle': { get: { summary: 'Shuttle Saatleri', tags: ['shuttle'] } },
      '/api/lounge': { get: { summary: 'Lounge Log', tags: ['lounge'] } },
      '/api/winecellar': { get: { summary: 'Şarap Mahzeni', tags: ['winecellar'] } },
      '/api/allergens': { get: { summary: 'Alerjen Matrisi', tags: ['allergens'] } },
      '/api/sustain': { get: { summary: 'Sürdürülebilirlik', tags: ['sustain'] } },
      '/api/mediakit': { get: { summary: 'Medya Kiti', tags: ['mediakit'] } },
      '/api/meetingrooms': { get: { summary: 'Toplantı Odaları', tags: ['meetingrooms'] } },
      '/api/badgeprint': { get: { summary: 'Kart Baskı', tags: ['badgeprint'] } },
      '/api/transfers': { get: { summary: 'Transfer Masası', tags: ['transfers'] } },
      '/api/beachbeds': { get: { summary: 'Şezlong', tags: ['beachbeds'] } },
      '/api/kidsclub': { get: { summary: 'Kids Club', tags: ['kidsclub'] } },
      '/api/lockers': { get: { summary: 'Dolap Kiralama', tags: ['lockers'] } },
      '/api/emergency': { get: { summary: 'Acil Rehber', tags: ['emergency'] } },
      '/api/kds': { get: { summary: 'KDS', tags: ['kds'] } },
      '/api/passstock': { get: { summary: 'Pass Stok', tags: ['passstock'] } },
      '/api/contracts': { get: { summary: 'Sözleşmeler', tags: ['contracts'] } },
      '/api/budget': { get: { summary: 'Bütçe', tags: ['budget'] } },
      '/api/pulse': { get: { summary: 'Ekip Nabız', tags: ['pulse'] } },
      '/api/content': { get: { summary: 'İçerik Kuyruğu', tags: ['content'] } },
      '/api/wifi': { get: { summary: 'WiFi Kupon', tags: ['wifi'] } },
      '/api/laundry': { get: { summary: 'Çamaşırhane', tags: ['laundry'] } },
      '/api/cleaning': { get: { summary: 'Temizlik', tags: ['cleaning'] } },
      '/api/delivery': { get: { summary: 'Paket Servis', tags: ['delivery'] } },
      '/api/giftcards': { get: { summary: 'Hediye Kartları', tags: ['giftcards'] } },
      '/api/eventcal': { get: { summary: 'Etkinlikler', tags: ['eventcal'] } },
      '/api/spa': { get: { summary: 'Spa / Wellness', tags: ['spa'] } },
      '/api/weather': { get: { summary: 'Hava brifi', tags: ['weather'] } },
      '/api/hours': { get: { summary: 'Çalışma saatleri', tags: ['hours'] } },
      '/api/kudos': { get: { summary: 'Takdir', tags: ['kudos'] } },
      '/api/complaints': { get: { summary: 'Şikayetler', tags: ['complaints'] } },
      '/api/waitlist': { get: { summary: 'Bekleme listesi', tags: ['waitlist'] } },
      '/api/seating': { get: { summary: 'Oturma planı', tags: ['seating'] } },
      '/api/waste': { get: { summary: 'Fire günlüğü', tags: ['waste'] } },
      '/api/vendor-scores': { get: { summary: 'Tedarikçi skor', tags: ['vendors'] } },
      '/api/documents': { get: { summary: 'Belge kasası', tags: ['documents'] } },
      '/api/music': { get: { summary: 'Müzik istekleri', tags: ['music'] } },
      '/api/valet': { get: { summary: 'Vale fişleri', tags: ['valet'] } },
      '/api/notifications': { get: { summary: 'Bildirimler', tags: ['notify'] } },
      '/api/events': { get: { summary: 'SSE olay akışı', tags: ['realtime'] } },
      '/api/settings': { get: { summary: 'Ayarlar', tags: ['settings'] } },
    },
  };
}
