/**
 * AŞAMA 11 — Sistem sağlığı ve data yedekleme / geri yükleme.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readCollection, writeCollection } from './store.js';
import { listVenues } from './venues.js';
import { jobsSummary } from './jobs.js';
import { getPublicSettings } from './settings.js';
import { sseClientCount } from './events.js';
import { appendAudit } from './audit.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.resolve(__dirname, '../data');

const BACKUP_COLLECTIONS = [
  'archive',
  'whatsapp',
  'nexus-events',
  'audit',
  'jobs',
  'settings',
  'venues',
  'notifications',
  'pass-holders',
  'access-events',
  'brands',
  'guests',
  'playbooks',
  'webhooks',
  'webhook-deliveries',
  'inventory',
  'inventory-movements',
  'shifts',
  'reservations',
  'loyalty-accounts',
  'loyalty-ledger',
  'incidents',
  'incident-acks',
  'suppliers',
  'purchase-orders',
  'feedback',
  'consents',
  'announcements',
  'recipes',
  'checklist-templates',
  'checklist-runs',
  'lost-found',
  'tip-pool',
  'tip-entries',
  'maintenance',
  'menu-items',
  'campaigns',
  'i18n-notes',
  'coldchain-assets',
  'coldchain-readings',
  'handover-notes',
  'cash-drawers',
  'cash-entries',
  'assets',
  'energy-meters',
  'energy-readings',
  'training-quizzes',
  'training-attempts',
  'venue-hours',
  'emergency-contacts',
  'mystery-scores',
  'partner-hotels',
  'shuttle-runs',
  'lounge-log',
  'wine-cellar',
  'allergens',
  'sustain-metrics',
  'media-kit',
  'meeting-rooms',
  'badge-prints',
  'transfers',
  'beach-beds',
  'kids-club',
  'lockers',
  'boardresolve3',
  'drplan3',
  'backupjob3',
  'failover4',
  'runbook3',
  'warroom23',
  'commsbridge23',
  'siteevac3',
  'coldsite3',
  'hotspare3',
  'drillscore3',
  'vendorfail3',
  'powercut3',
  'netsplit3',
  'ipvault3',
  'legaldesk3',
  'riskreg3',
  'policyhub3',
  'claimdesk3',
  'insurancet3',
  'litigation3',
  'compliance23',
  'ethicsline3',
  'kycrow3',
  'sanctions3',
  'datapriv3',
  'retentionpol3',
  'auditevidence3',
  'cohort3',
  'labbench3',
  'pilotrun3',
  'prototype3',
  'hypothesis3',
  'metricslab3',
  'userboard3',
  'patentdesk3',
  'sandbox3',
  'hackday3',
  'incubate3',
  'spindesk3',
  'researchnote3',
  'labbudget3',
  'chaosdrill3',
  'memberhub3',
  'circle3',
  'meetup3',
  'forummod3',
  'polldesk3',
  'badgeearn3',
  'questline3',
  'volunteer3',
  'donation3',
  'chapter3',
  'ambassador23',
  'storywall3',
  'ritualcal3',
  'momentmap3',
  'apigateway3',
  'webhookhub3',
  'ratelimit23',
  'schemareg3',
  'eventbus3',
  'jobqueue23',
  'cachemesh3',
  'cdnedge3',
  'observemap3',
  'errorbudget4',
  'featuregate3',
  'canaryrun3',
  'rollback3',
  'legacyflag3',
  'calmroom3',
  'quiethours3',
  'scentmood3',
  'pillowmenu4',
  'bathritual3',
  'sleepscore3',
  'welcomeamen3',
  'farewell3',
  'memorybook3',
  'carecall3',
  'surprisegift3',
  'loyaltyhug3',
  'feedbackloop3',
  'supplierkpi3',
  'cmdpulse3',
  'boardpulse3',
  'riskheat3',
  'cashpulse3',
  'opsheat3',
  'guestheat3',
  'brandheat3',
  'agentpulse3',
  'systempulse3',
  'alertfuse3',
  'warbrief3',
  'decisionhub3',
  'sealnote3',
  'inboundpo3',
  'outboundso3',
  'asntrack3',
  'dockyard3',
  'crossdock3',
  'coldchain23',
  'slotbook3',
  'carrierbid3',
  'freightbill3',
  'milestonet3',
  'exceptionlog3',
  'inventoryage3',
  'replenplan3',
  'safetystock3',
  'partnerdesk3',
  'franchise3',
  'channelkit3',
  'rebate3',
  'coinvest3',
  'slatrack3',
  'jointpromo3',
  'leadshare3',
  'b2border3',
  'wholesale3',
  'dealroom3',
  'contractrow3',
  'commission3',
  'onboardkit3',
  'accessgate3',
  'idproof3',
  'rolegrant3',
  'sessionguard3',
  'devicetrust3',
  'secretvault3',
  'mfareg3',
  'ssobridge3',
  'privacypol3',
  'consentrow3',
  'breachlog3',
  'socqueue3',
  'patchdesk3',
  'zerohour3',
  'boardresolve2',
  'drplan2',
  'backupjob2',
  'failover3',
  'runbook2',
  'warroom22',
  'commsbridge22',
  'siteevac2',
  'coldsite2',
  'hotspare2',
  'drillscore2',
  'vendorfail2',
  'powercut2',
  'netsplit2',
  'ipvault2',
  'legaldesk2',
  'riskreg2',
  'policyhub2',
  'claimdesk2',
  'insurancet2',
  'litigation2',
  'compliance22',
  'ethicsline2',
  'kycrow2',
  'sanctions2',
  'datapriv2',
  'retentionpol2',
  'auditevidence2',
  'cohort2',
  'labbench2',
  'pilotrun2',
  'prototype2',
  'hypothesis2',
  'metricslab2',
  'userboard2',
  'patentdesk2',
  'sandbox2',
  'hackday2',
  'incubate2',
  'spindesk2',
  'researchnote2',
  'labbudget2',
  'chaosdrill2',
  'memberhub2',
  'circle2',
  'meetup2',
  'forummod2',
  'polldesk2',
  'badgeearn2',
  'questline2',
  'volunteer2',
  'donation2',
  'chapter2',
  'ambassador22',
  'storywall2',
  'ritualcal2',
  'momentmap2',
  'apigateway2',
  'webhookhub2',
  'ratelimit22',
  'schemareg2',
  'eventbus2',
  'jobqueue22',
  'cachemesh2',
  'cdnedge2',
  'observemap2',
  'errorbudget3',
  'featuregate2',
  'canaryrun2',
  'rollback2',
  'legacyflag2',
  'calmroom2',
  'quiethours2',
  'scentmood2',
  'pillowmenu3',
  'bathritual2',
  'sleepscore2',
  'welcomeamen2',
  'farewell2',
  'memorybook2',
  'carecall2',
  'surprisegift2',
  'loyaltyhug2',
  'feedbackloop2',
  'supplierkpi2',
  'cmdpulse2',
  'boardpulse2',
  'riskheat2',
  'cashpulse2',
  'opsheat2',
  'guestheat2',
  'brandheat2',
  'agentpulse2',
  'systempulse2',
  'alertfuse2',
  'warbrief2',
  'decisionhub2',
  'sealnote2',
  'inboundpo2',
  'outboundso2',
  'asntrack2',
  'dockyard2',
  'crossdock2',
  'coldchain22',
  'slotbook2',
  'carrierbid2',
  'freightbill2',
  'milestonet2',
  'exceptionlog2',
  'inventoryage2',
  'replenplan2',
  'safetystock2',
  'partnerdesk2',
  'franchise2',
  'channelkit2',
  'rebate2',
  'coinvest2',
  'slatrack2',
  'jointpromo2',
  'leadshare2',
  'b2border2',
  'wholesale2',
  'dealroom2',
  'contractrow2',
  'commission2',
  'onboardkit2',
  'accessgate2',
  'idproof2',
  'rolegrant2',
  'sessionguard2',
  'devicetrust2',
  'secretvault2',
  'mfareg2',
  'ssobridge2',
  'privacypol2',
  'consentrow2',
  'breachlog2',
  'socqueue2',
  'patchdesk2',
  'zerohour2',
  'storyvault',
  'olympulse',
  'holdingseal',
  'agentcourt',
  'finalbrief',
  'legacycode',
  'eternallog',
  'summitnote',
  'constellate',
  'mythos',
  'aegisfinal',
  'crownfinal',
  'vaultfinal',
  'empirefinal',
  'corrective',
  'archivebox',
  'oralhistory',
  'artifact',
  'timeline',
  'foundersnote',
  'brandbible',
  'museumdesk',
  'heritage',
  'anniversary',
  'alumni',
  'scholarship',
  'foundation',
  'legacygift',
  'postlaunch',
  'qasample',
  'defectlog',
  'standardop',
  'mysteryguest',
  'npsdeep',
  'servicemark',
  'calibdesk',
  'labresult',
  'certrenew',
  'isotrack',
  'guestvoice',
  'fixgate',
  'rootcause',
  'restorejob',
  'marketscan',
  'sitehunt',
  'capextable',
  'softopen',
  'launchpad',
  'localhire',
  'permitdesk',
  'landlease',
  'buildphase',
  'ffespec',
  'brandrollout',
  'trainwave',
  'golive',
  'boardresolve',
  'drplan',
  'backupjob',
  'failover2',
  'runbook',
  'warroom2',
  'commsbridge2',
  'siteevac',
  'coldsite',
  'hotspare',
  'drillscore',
  'vendorfail',
  'powercut',
  'netsplit',
  'ipvault',
  'legaldesk',
  'riskreg',
  'policyhub',
  'claimdesk',
  'insurancet',
  'litigation',
  'compliance2',
  'ethicsline',
  'kycrow',
  'sanctions',
  'datapriv',
  'retentionpol',
  'auditevidence',
  'cohort',
  'labbench',
  'pilotrun',
  'prototype',
  'hypothesis',
  'metricslab',
  'userboard',
  'patentdesk',
  'sandbox',
  'hackday',
  'incubate',
  'spindesk',
  'researchnote',
  'labbudget',
  'chaosdrill',
  'memberhub',
  'circle',
  'meetup',
  'forummod',
  'polldesk',
  'badgeearn',
  'questline',
  'volunteer',
  'donation',
  'chapter',
  'ambassador2',
  'storywall',
  'ritualcal',
  'momentmap',
  'apigateway',
  'webhookhub',
  'ratelimit2',
  'schemareg',
  'eventbus',
  'jobqueue2',
  'cachemesh',
  'cdnedge',
  'observemap',
  'errorbudget2',
  'featuregate',
  'canaryrun',
  'rollback',
  'legacyflag',
  'calmroom',
  'quiethours',
  'scentmood',
  'pillowmenu2',
  'bathritual',
  'sleepscore',
  'welcomeamen',
  'farewell',
  'memorybook',
  'carecall',
  'surprisegift',
  'loyaltyhug',
  'feedbackloop',
  'supplierkpi',
  'cmdpulse',
  'boardpulse',
  'riskheat',
  'cashpulse',
  'opsheat',
  'guestheat',
  'brandheat',
  'agentpulse',
  'systempulse',
  'alertfuse',
  'warbrief',
  'decisionhub',
  'sealnote',
  'inboundpo',
  'outboundso',
  'asntrack',
  'dockyard',
  'crossdock',
  'coldchain2',
  'slotbook',
  'carrierbid',
  'freightbill',
  'milestonet',
  'exceptionlog',
  'inventoryage',
  'replenplan',
  'safetystock',
  'partnerdesk',
  'franchise',
  'channelkit',
  'rebate',
  'coinvest',
  'slatrack',
  'jointpromo',
  'leadshare',
  'b2border',
  'wholesale',
  'dealroom',
  'contractrow',
  'commission',
  'onboardkit',
  'accessgate',
  'idproof',
  'rolegrant',
  'sessionguard',
  'devicetrust',
  'secretvault',
  'mfareg',
  'ssobridge',
  'privacypol',
  'consentrow',
  'breachlog',
  'socqueue',
  'patchdesk',
  'zerohour',
  'carbonledger',
  'wateruse',
  'wastesort',
  'energybid',
  'solaryield',
  'greenteam',
  'esgaudit',
  'biosurvey',
  'offsetbuy',
  'climategoal',
  'greenbond',
  'plasticaudit',
  'evcharger',
  'reefwatch',
  'mediawall',
  'contentrights',
  'adslot',
  'sponsorpack',
  'brandambass',
  'creatorpay',
  'ugcqueue',
  'pressroom',
  'livecast',
  'eventstream',
  'affiliatenet',
  'boostdesk',
  'assetlib',
  'briefdesk',
  'retailfloor',
  'planogram',
  'shelfscan',
  'priceaudit',
  'shrinklog',
  'vendorportal',
  'assortmix',
  'promoplane',
  'categorybuy',
  'demandplan',
  'stockhealth',
  'returnbay',
  'darkstore',
  'poslane',
  'tybridge',
  'dolaplist',
  'hephapick',
  'tourpack',
  'rentgear',
  'wareserve',
  'staybook',
  'dazeroom',
  'keylessdoor',
  'sportslot',
  'arenabook',
  'nexusgate',
  'mintbundle',
  'packfolio',
  'nightaudit',
  'foliodesk',
  'deskqueue',
  'wakeall',
  'earlycheck',
  'latecheck',
  'bagstore',
  'callsheet',
  'arrivalboard',
  'departureboard',
  'viparrive',
  'frontlog',
  'moveticket',
  'conciergejob',
  'roomrack',
  'hkboard',
  'linenroom',
  'minibarbay',
  'foundlog',
  'keydesk',
  'turnup',
  'deepclean',
  'inspectroom',
  'vipprep',
  'outoforder',
  'guestrequest',
  'amensave',
  'publicarea',
  'shuttlelane',
  'fleetdesk',
  'driverost',
  'fuelcard',
  'routeplan',
  'dispatchboard',
  'gpsping',
  'vehiclemaint',
  'valetops',
  'parkingbay',
  'transferjob',
  'pickupdrop',
  'tollpass',
  'lanecontrol',
  'treasury',
  'cashflow',
  'apdesk',
  'ardesk',
  'invoicedesk',
  'taxdesk',
  'budgetline',
  'fxdesk',
  'bankrecon',
  'payout',
  'pettycash',
  'costcenter',
  'glmap',
  'closebook',
  'campdesk',
  'contentcal',
  'socialqueue',
  'creatordesk',
  'utmtrack',
  'landing',
  'abcopy',
  'seopage',
  'pushdesk',
  'emailblast',
  'presspack',
  'brandkit',
  'mediabuy',
  'leadmagnet',
  'memberdesk',
  'tierladder',
  'pointledger',
  'perkshop',
  'referral',
  'giftcard',
  'vipdesk',
  'stayhistory',
  'prefernote',
  'npspulse',
  'guestcase',
  'praise',
  'winback',
  'clubnight',
  'datalake',
  'featureflag',
  'modelcard',
  'promptlab',
  'evalbench',
  'datasetcat',
  'lineage',
  'vectorstore',
  'insightboard',
  'anomaly',
  'demandcast',
  'abtest',
  'scorecard',
  'decidlog',
  'safetylog',
  'incidentlog',
  'hazardnote',
  'evacroute',
  'drillrun',
  'aidkit',
  'hazmatbay',
  'ppekit',
  'lockouttag',
  'permitwork',
  'compliancerow',
  'audittrail2',
  'cctvreview',
  'guestsafety',
  'talentdesk',
  'shiftbid',
  'skillmatrix',
  'certtrack',
  'traininghub',
  'mentorship',
  'succession',
  'payrollrun',
  'performnote',
  'reviewcycle',
  'headcount',
  'attrition',
  'culturepulse',
  'shifttrade',
  'assetmap',
  'plantroom',
  'hvacloop',
  'waterloop',
  'powergrid',
  'elevatorlog',
  'spareparts',
  'workorder',
  'leasehold',
  'tenantops',
  'facilitytour',
  'capexdesk',
  'opexdesk',
  'estatescan',
  'spaflow',
  'thermalbay',
  'saunalog',
  'cryochamber',
  'floatpod',
  'massagebook',
  'yogamat',
  'breathwork',
  'recoverybay',
  'ivlounge',
  'sleepcoach',
  'nutrition',
  'biomarker',
  'wellnesskit',
  'miseplan',
  'passrail',
  'plateup',
  'gardebay',
  'pastrylab',
  'tastingmenu',
  'cellarbox',
  'barrail',
  'roomservice',
  'caterdesk',
  'allergenmap',
  'wastekitchen',
  'chefbrief',
  'supplypull',
  'auroradeck',
  'lightshow',
  'soundscape',
  'scentzone',
  'moodlight',
  'fogscene',
  'projection',
  'immersive',
  'hapticcue',
  'atmosmix',
  'guestflow',
  'scenectrl',
  'nightmode',
  'dawnmode',
  'harborlane',
  'dockslot',
  'craneops',
  'container',
  'coldbay',
  'yardmove',
  'gatepass',
  'bolthold',
  'manifest',
  'demurrage',
  'pilotage',
  'tugassist',
  'wharfage',
  'stevedore',
  'tidewatch',
  'duneops',
  'snorkelbay',
  'cliffpath',
  'campglow',
  'lookout',
  'reefguard',
  'pierops',
  'saildesk',
  'umbrellamap',
  'sandclean',
  'nightswim',
  'stargaze',
  'coastpatrol',
  'masterplan',
  'okrrack',
  'roadmap',
  'betboard',
  'portfoliorisk',
  'captable',
  'boardmotion',
  'alliance',
  'expansion',
  'legacyarc',
  'culturecode',
  'talentbet',
  'moatwatch',
  'northstar',
  'revstream',
  'packagemix',
  'ancillary',
  'dynamicbundle',
  'pricefloor',
  'compset',
  'pickuppace',
  'noshowrisk',
  'walkinflow',
  'tableturn',
  'beatrevenue',
  'cashforecast',
  'marginwatch',
  'promoattr',
  'incidentbus',
  'playtrigger',
  'escalation',
  'warroomseat',
  'decisionlog',
  'slotrack',
  'errorbudget',
  'changewindow',
  'blameless',
  'pagerduty',
  'statuspage',
  'runbooklink',
  'commsbridge',
  'afteraction',
  'guesttwin',
  'prefgraph',
  'intentscore',
  'nextbest',
  'journeymap',
  'microseg',
  'offerlab',
  'consentgraph',
  'emotionpulse',
  'servicememory',
  'recoverypath',
  'lifetimeval',
  'churnrisk',
  'wowmoment',
  'edgegate',
  'meshlink',
  'radiomesh',
  'sensorfuse',
  'otafirm',
  'devinventory',
  'powerbudget',
  'backhaul',
  'edgecache2',
  'syncrepl',
  'failover',
  'telemetry',
  'netslice',
  'satlink',
  'posbridge',
  'dynamint',
  'couriertrack',
  'autocheckout',
  'loyaltyburn',
  'treatoffer',
  'omnimarket',
  'clickcollect',
  'lastmile',
  'invsync',
  'pricepush',
  'qrpay',
  'courierpool',
  'giftrelay',
  'modelops',
  'promptlib',
  'agenteval',
  'tokenbudget',
  'ragindex',
  'toolpermit',
  'sandboxrun',
  'hallucheck',
  'datasetcur',
  'redteam',
  'slaagent',
  'costguard',
  'latencylog',
  'driftmonitor',
  'presskit',
  'influencer',
  'ugcmod',
  'seoaudit',
  'adspend',
  'brandguard',
  'storyboard',
  'livestream',
  'podcastshow',
  'newsletter',
  'tagmap',
  'socialinbox',
  'mediaembargo',
  'creativereq',
  'carbonlog',
  'wateraudit',
  'airquality',
  'solarops',
  'biodiversity',
  'recycling',
  'greencert',
  'auditfind',
  'policyack',
  'dataprotect',
  'retention',
  'accessreview',
  'vendorrisk',
  'legalhold',
  'onboarding',
  'offboarding',
  'interviews',
  'certifications',
  'langskill',
  'shiftswap',
  'leaverequest',
  'attendance',
  'performance',
  'recognition',
  'handbook',
  'safetybrief',
  'nearmiss',
  'whistle',
  'arbill',
  'apbill',
  'bankrec',
  'fxrates',
  'tipout',
  'deposit',
  'refunds',
  'chargeback',
  'giftred',
  'memberbill',
  'rateplan',
  'channelmgr',
  'overbook',
  'yieldrule',
  'stayext',
  'roommove',
  'earlyin',
  'luggage',
  'turndown',
  'pillowmenu',
  'scenting',
  'dndflags',
  'bathstock',
  'ironreq',
  'pressing',
  'shoeshine',
  'babycot',
  'petstay',
  'menuboard',
  'allergenalert',
  'tempprobe',
  'prepqueue',
  'voidlog',
  'comps',
  'splitbill',
  'tabopen',
  'corkage',
  'sommelier',
  'chefnote',
  'passticket',
  'zoneheat',
  'revpulse',
  'crowddens',
  'queuetimes',
  'lostchild',
  'firstaid',
  'aedcheck',
  'evacdrill',
  'crowdctrl',
  'radiolog',
  'gatequeue',
  'wristscan',
  'facepass',
  'bagcheck',
  'metaldet',
  'watchlist',
  'helipad',
  'jetski',
  'yacht',
  'surfschool',
  'paddle',
  'climwall',
  'escaperoom',
  'arcade',
  'bowling',
  'billiards',
  'pokertable',
  'trivia',
  'djbooth',
  'soundcheck',
  'signage',
  'wayfind',
  'beaconmap',
  'iotgates',
  'powerops',
  'waterops',
  'greenops',
  'pestctrl',
  'chemlog',
  'poolops',
  'saunaops',
  'steamops',
  'icebath',
  'recovslots',
  'extlinks',
  'apikeys',
  'backupsched',
  'sysalerts',
  'bugtracker',
  'releasenotes',
  'runbooks',
  'biometrics',
  'secretsrot',
  'dnscheck',
  'mailqueue',
  'smsqueue',
  'alertrules',
  'edgecache',
  'rosters',
  'overtime',
  'uniforms',
  'healthcards',
  'visitors',
  'cctvlog',
  'firedrill',
  'insurance',
  'invoices',
  'taxpack',
  'forecast',
  'capex',
  'licenses',
  'slabreaches',
  'keycards',
  'roomstatus',
  'bedding',
  'wakeups',
  'parcels',
  'qrcheckin',
  'guestapp',
  'karaoke',
  'artwall',
  'florals',
  'privatechef',
  'mocktails',
  'promos',
  'dawnservice',
  'upsell',
  'otareviews',
  'groups',
  'vipnotes',
  'photoshoot',
  'dive',
  'bikerent',
  'cinema',
  'retail',
  'bakery',
  'breakfast',
  'lateout',
  'amenities',
  'nightlog',
  'concierge',
  'minibar',
  'folio',
  'banquet',
  'tours',
  'marina',
  'hammam',
  'towels',
  'bands',
  'haccp',
  'patrol',
  'fleet',
  'payroll',
  'flash',
  'kds-tickets',
  'pass-stock',
  'contracts',
  'budget-lines',
  'staff-pulse',
  'content-queue',
  'wifi-vouchers',
  'laundry-batches',
  'cleaning-tasks',
  'delivery-orders',
  'gift-cards',
  'events-calendar',
  'spa-bookings',
  'kudos',
  'complaints',
  'waitlist',
  'seating',
  'waste-log',
  'vendor-scores',
  'documents',
  'music-requests',
  'valet-tickets',
  // sessions bilinçli olarak yedeğe alınabilir ama restore'da opsiyonel
  'campus-zones',
  'campus-incidents',
  'stay-units',
  'stay-bookings',
  'club-athletes',
  'athlete-plans',
  'athlete-sessions',
  'life-clients',
  'life-metrics',
  'life-plans',
  'market-listings',
  'market-orders',
  'mall-tenants',
  'mall-sales',
  'family-programs',
  'family-checkins',
  'family-staff-ratio-sweeps',
  'family-roll-calls',
  'family-staff',
  'extreme-members',
  'extreme-slots',
  'extreme-waivers',
  'extreme-gear',
  'extreme-maas',
  'extreme-weather-hold-sweeps',
  'extreme-wallet-topups',
  'extreme-maas-renewals',
  'extreme-notices',
  'market-channel-syncs',
  'agent-jobs',
  'green-incidents',
  'agent-pings',
  'agent-presence',
  'agent-bridge-alerts',
  'agent-bridge-sla-sweeps',
  'agent-bridge-alert-routes',
  'agent-bridge-channels',
  'fleet-directives',
  'fleet-handoffs',
  'fleet-shifts',
  'campus-brief-digests',
  'agent-queue-archives',
  'agent-queue-rebalances',
  'agent-jobs-archive',
  'campus-work-order-sweeps',
  'campus-work-orders',
  'campus-work-order-escalations',
  'campus-work-order-assignments',
  'market-low-stock-sweeps',
  'market-purchase-orders',
  'sport-gate-checks',
  'sport-postcomp-sweeps',
  'sport-recovery-closeouts',
  'sport-comp-holds',
  'life-adherence',
  'life-missed-checkin-sweeps',
  'life-missed-checkins',
  'life-crisis-clears',
  'life-crises',
  'life-followups',
  'green-water-triage',
  'green-work-permits',
  'green-curtailment-clears',
  'green-curtailments',
  'green-permit-expiry-sweeps',
  'athlete-rtp-sweeps',
  'athlete-rtp-events',
  'athlete-injuries',
  'culture-settlements',
  'culture-refunds',
  'culture-hold-expiries',
  'family-safety-sweeps',
  'family-custody-ledger',
  'family-pickup-codes',
  'family-pickup-expiry-sweeps',
  'family-program-cancels',
  'family-pickup-noshows',
  'mall-dunning-sweeps',
  'mall-payments',
  'mall-invoices',
  'mall-lease-holds',
  'mall-tenant-resumes',
  'mall-tenant-pauses',
  'mall-invoice-disputes',
  'mall-cam-runs',
  'stay-folio-settlements',
  'stay-folio-charges',
  'extreme-gear-sweeps',
  'extreme-gear-ledger',
  'life-digests',
  'culture-box-office',
  'athlete-clearances',
  'athlete-comp-clearance-sweeps',
  'athlete-comp-clearances',
  'athlete-competitions',
  'athlete-medical-hold-clears',
  'athlete-medical-holds',
  'athlete-coach-assignments',
  'stay-guest-requests',
  'green-batches',
  'market-reconciles',
  'extreme-waitlist',
  'extreme-waitlist-expires',
  'family-transfers',
  'agent-broadcasts',
  'campus-capacity-rollups',
  'campus-capacity-alert-sweeps',
  'campus-capacity-alerts',
  'campus-zone-lockdown-clears',
  'campus-zone-lockdowns',
  'campus-incident-escalations',
  'mall-fnb-settlements',
  'culture-streams',
  'campus-brief-actions',
  'green-automations',
  'sport-eligibility',
  'extreme-reservations',
  'stay-night-rollups',
  'stay-overstays',
  'stay-key-revocations',
  'stay-folio-disputes',
  'stay-late-checkouts',
  'stay-night-audits',
  'life-checkins',
  'mall-day-rollups',
  'market-returns',
  'market-rental-sweeps',
  'market-deposit-settlements',
  'market-damage-assessments',
  'market-rental-overdues',
  'culture-sales',
  'culture-crew-calls',
  'culture-door-scans',
  'culture-hold-transfers',
  'culture-vip-upgrades',
  'family-notes',
  'family-bookings',
  'green-readings',
  'green-meters',
  'life-webhooks',
  'life-devices',
  'sport-syncs',
  'sport-links',
  'culture-holds',
  'culture-events',
  'culture-stages',
  'stay-hk',
  'stay-keys',
  'sessions',
];

export function healthCheck() {
  const settings = getPublicSettings();
  const jobs = jobsSummary();
  const venues = listVenues();
  let dataOk = true;
  try {
    if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
    fs.accessSync(DATA_DIR, fs.constants.W_OK);
  } catch {
    dataOk = false;
  }

  let campus = null;
  try {
    // dinamik — döngüsel bağımlılık riskini azalt
    campus = null;
  } catch {
    campus = null;
  }

  const checks = {
    dataDirWritable: dataOk,
    venuesSeeded: venues.length > 0,
    settingsConfigured: settings.fields.filter((f) => f.configured).length,
    jobsTotal: jobs.total,
    sseClients: sseClientCount(),
    ollamaUrl: process.env.OLLAMA_HOST || 'http://localhost:11434',
  };

  let status =
    !dataOk ? 'unhealthy' : checks.settingsConfigured === 0 ? 'degraded' : 'healthy';

  return {
    status,
    service: 'olympospass-likya-panel',
    version: '1.0.0',
    uptimeSec: Math.round(process.uptime()),
    generatedAt: new Date().toISOString(),
    checks,
    campus,
  };
}

export async function healthCheckAsync() {
  const base = healthCheck();
  try {
    const { campusHealthCheck } = await import('./campusbrief.js');
    const campus = campusHealthCheck();
    let status = base.status;
    if (campus.status === 'unhealthy') status = 'unhealthy';
    else if (campus.status === 'degraded' && status === 'healthy') status = 'degraded';
    return { ...base, status, campus };
  } catch {
    return base;
  }
}

export function createBackup() {
  const collections = {};
  for (const name of BACKUP_COLLECTIONS) {
    const fallback = name === 'settings' || name === 'sessions' ? {} : [];
    collections[name] = readCollection(name, fallback);
  }
  return {
    format: 'likya-backup-v1',
    createdAt: new Date().toISOString(),
    collections,
  };
}

export function restoreBackup(payload, actor = 'system') {
  if (!payload || payload.format !== 'likya-backup-v1' || !payload.collections) {
    throw new Error('Geçersiz yedek formatı (likya-backup-v1 bekleniyor)');
  }
  const restored = [];
  for (const [name, data] of Object.entries(payload.collections)) {
    if (!BACKUP_COLLECTIONS.includes(name)) continue;
    writeCollection(name, data);
    restored.push(name);
  }
  appendAudit({
    actor,
    action: 'ops.restore',
    detail: `Yedek geri yüklendi: ${restored.join(', ')}`,
    meta: { restored, backupAt: payload.createdAt },
  });
  return { ok: true, restored, backupAt: payload.createdAt };
}

export function listDataFiles() {
  if (!fs.existsSync(DATA_DIR)) return [];
  return fs
    .readdirSync(DATA_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => {
      const st = fs.statSync(path.join(DATA_DIR, f));
      return { name: f, bytes: st.size, mtime: st.mtime.toISOString() };
    });
}

const CAMPUS_CRITICAL = [
  'agent-jobs',
  'campus-brief-actions',
  'agent-bridge-alerts',
  'fleet-directives',
  'sport-comp-holds',
  'readiness-snapshots',
];

function rid(p) {
  return `${p}_${Date.now().toString(36)}_${Math.random().toString(16).slice(2, 6)}`;
}

/** Data dosya bütünlük taraması */
export function runOpsIntegritySweep(input = {}, actor = 'system') {
  const files = listDataFiles();
  const issues = [];
  const quarantine = readCollection('ops-quarantine', []) || [];
  const qSet = new Set((Array.isArray(quarantine) ? quarantine : []).filter((q) => q.status === 'active').map((q) => q.file));

  for (const f of files) {
    if (qSet.has(f.name)) {
      issues.push({ file: f.name, kind: 'quarantined', detail: 'karantina aktif' });
      continue;
    }
    if (f.bytes === 0) {
      issues.push({ file: f.name, kind: 'empty', detail: '0 byte' });
      continue;
    }
    try {
      const raw = fs.readFileSync(path.join(DATA_DIR, f.name), 'utf8');
      JSON.parse(raw);
    } catch (err) {
      issues.push({
        file: f.name,
        kind: 'corrupt',
        detail: err instanceof Error ? err.message : 'parse error',
      });
    }
  }

  for (const col of CAMPUS_CRITICAL) {
    const file = `${col}.json`;
    if (!files.some((f) => f.name === file) && input.force) {
      issues.push({ file, kind: 'missing', detail: 'kritik koleksiyon yok' });
    }
  }

  const sweep = {
    id: rid('ois'),
    scanned: files.length,
    issues: issues.length,
    items: issues.slice(0, 80),
    at: new Date().toISOString(),
    actor,
  };
  const history = readCollection('ops-integrity-sweeps', []) || [];
  writeCollection('ops-integrity-sweeps', [sweep, ...(Array.isArray(history) ? history : [])].slice(0, 80));
  appendAudit({
    actor,
    action: 'ops.integrity_sweep',
    detail: `${files.length} dosya · ${issues.length} issue`,
    meta: { id: sweep.id },
  });
  return {
    ok: true,
    sweep,
    issues,
    overview: { health: healthCheck(), files: files.length, quarantine: qSet.size },
  };
}

/** Yedek rotate — metadata + koleksiyon sayısı snapshot */
export function rotateOpsBackup(input = {}, actor = 'system') {
  const backup = createBackup();
  const keys = Object.keys(backup.collections || {});
  const row = {
    id: rid('obr'),
    createdAt: backup.createdAt,
    collections: keys.length,
    note: String(input.note || '').slice(0, 240) || undefined,
    // tam dump değil — özet (disk dostu)
    sample_keys: keys.slice(0, 40),
    at: new Date().toISOString(),
    actor,
  };
  const list = readCollection('ops-backup-rotations', []) || [];
  const next = [row, ...(Array.isArray(list) ? list : [])].slice(0, Number(input.keep) || 40);
  writeCollection('ops-backup-rotations', next);
  appendAudit({
    actor,
    action: 'ops.backup_rotate',
    detail: `${row.collections} koleksiyon`,
    meta: { id: row.id },
  });
  return { ok: true, rotation: row, overview: { rotations: next.length, health: healthCheck() } };
}

/** Bozuk / şüpheli dosyayı karantinaya al */
export function quarantineOpsFile(input = {}, actor = 'system') {
  const file = String(input.file || input.name || '').replace(/[^a-zA-Z0-9._-]/g, '');
  if (!file.endsWith('.json')) return { ok: false, error: 'Geçersiz dosya adı' };
  const full = path.join(DATA_DIR, file);
  if (!fs.existsSync(full)) return { ok: false, error: 'Dosya yok' };
  const row = {
    id: rid('oqf'),
    file,
    status: 'active',
    reason: String(input.reason || 'quarantine').slice(0, 240),
    at: new Date().toISOString(),
    actor,
  };
  const list = readCollection('ops-quarantine', []) || [];
  const arr = Array.isArray(list) ? list.filter((q) => !(q.file === file && q.status === 'active')) : [];
  arr.unshift(row);
  writeCollection('ops-quarantine', arr.slice(0, 200));
  appendAudit({
    actor,
    action: 'ops.quarantine',
    detail: file,
    meta: { id: row.id },
  });
  return { ok: true, quarantine: row, overview: { quarantine_active: arr.filter((q) => q.status === 'active').length } };
}

/** Karantina / degraded bayraklarını temizle */
export function clearOpsDegraded(input = {}, actor = 'system') {
  const list = readCollection('ops-quarantine', []) || [];
  const arr = Array.isArray(list) ? [...list] : [];
  let cleared = 0;
  for (let i = 0; i < arr.length; i++) {
    if (arr[i].status !== 'active') continue;
    if (input.file && arr[i].file !== input.file) continue;
    arr[i] = {
      ...arr[i],
      status: 'cleared',
      cleared_at: new Date().toISOString(),
      cleared_by: actor,
      clear_reason: String(input.reason || 'cleared').slice(0, 240),
    };
    cleared++;
  }
  if (!cleared && input.force) {
    // force: boş kayıt
    cleared = 0;
  }
  writeCollection('ops-quarantine', arr);
  const flag = {
    id: rid('ocd'),
    cleared,
    at: new Date().toISOString(),
    actor,
  };
  const hist = readCollection('ops-degraded-clears', []) || [];
  writeCollection('ops-degraded-clears', [flag, ...(Array.isArray(hist) ? hist : [])].slice(0, 60));
  appendAudit({
    actor,
    action: 'ops.clear_degraded',
    detail: `${cleared} karantina`,
    meta: { id: flag.id },
  });
  return {
    ok: true,
    cleared,
    flag,
    overview: { health: healthCheck(), quarantine_active: arr.filter((q) => q.status === 'active').length },
  };
}
