import {
  Bot,
  ChefHat,
  Cpu,
  HeartHandshake,
  LayoutDashboard,
  LogOut,
  Mountain,
  Network,
  Radio,
  BarChart3,
  Bell,
  Building2,
  HardDrive,
  ListTodo,
  MapPin,
  Settings,
  ShieldCheck,
  TabletSmartphone,
  Ticket,
  UserRound,
  Users,
  Webhook,
  Package,
  CalendarClock,
  BookOpen,
  CalendarCheck,
  Gift,
  AlertTriangle,
  Truck,
  MessageSquareHeart,
  Download,
  Scale,
  Megaphone,
  UtensilsCrossed,
  ClipboardCheck,
  Search,
  Coins,
  ScrollText,
  Wrench,
  Sunrise,
  Utensils,
  BadgePercent,
  Languages,
  Thermometer,
  NotebookPen,
  Wallet,
  Boxes,
  Zap,
  Car,
  Music2,
  FileText,
  Star,
  Trash2,
  Armchair,
  ListOrdered,
  MessageCircleWarning,
  Award,
  Clock3,
  CloudSun,
  Gauge,
  Sparkles,
  CalendarDays,
  CreditCard,
  Bike,
  SprayCan,
  Shirt,
  Wifi,
  Images,
  Activity,
  Landmark,
  FileSignature,
  ScanBarcode,
  MonitorPlay,
  PhoneCall,
  Newspaper,
  GraduationCap,
  Lock,
  Baby,
  Palmtree,
  Plane,
  Printer,
  Presentation,
  Clapperboard,
  Leaf,
  ShieldAlert,
  Wine,
  Sofa,
  Bus,
  Hotel,
  Eye,
  BriefcaseBusiness,
  ConciergeBell,
  Receipt,
  PartyPopper,
  MapPinned,
  Anchor,
  Bath,
  Watch,
  ClipboardList,
  Shield,
  Banknote,
  Radar,
  TrendingUp,
  MessageSquareQuote,
  UsersRound,
  Crown,
  Camera,
  Waves,
  ShoppingBag,
  Croissant,
  Coffee,
  MoonStar,
  Telescope,
  KeyRound,
  DoorOpen,
  BedDouble,
  AlarmClock,
  PackageCheck,
  QrCode,
  Smartphone,
  Mic2,
  Palette,
  Flower2,
  GlassWater,
  TicketPercent,
  Orbit,
  CalendarRange,
  Timer,
  HeartPulse,
  IdCard,
  Cctv,
  Flame,
  ShieldPlus,
  FileSpreadsheet,
  Calculator,
  LineChart,
  Building,
  Stamp,
  TriangleAlert,
  MountainSnow,
  PlugZap,
  KeySquare,
  DatabaseBackup,
  ServerCrash,
  Bug,
  GitBranch,
  Terminal,
  Fingerprint,
  Globe2,
  Mail,
  MessageCircle,
  BellRing,
  CloudFog,
  Pyramid,
  FlaskConical,
  Snowflake,
  SatelliteDish,
  PlaneTakeoff,
  Ship,
  Sailboat,
  Wind,
  BrickWall,
  DoorClosed,
  Joystick,
  Target,
  CircleDot,
  Spade,
  HelpCircle,
  Disc3,
  AudioLines,
  Castle,
  Siren,
  ScanFace,
  Briefcase,
  ScanLine,
  Ban,
  Split,
  Footprints,
  PawPrint,
  Compass,
  ReceiptText,
  WalletCards,
  BadgeDollarSign,
  PiggyBank,
  TrendingDown,
  Percent,
  Globe,
  Layers,
  BookMarked,
  ArrowLeftRight,
  Trophy,
  HardHat,
  Factory,
  Droplets,
  Fan,
  SunMedium,
  TreeDeciduous,
  Recycle,
  BadgeCheck,
  FileCheck2,
  Gavel,
  Share2,
  Video,
  Podcast,
  Hash,
  PenLine,
  Swords,
  BrainCircuit,
  Store,
  CandlestickChart,
  Route,
  RefreshCw,
  Tags,
  Rocket,
  Router,
  RadioTower,
  Antenna,
  CloudUpload,
  Cable,
  CloudDownload,
  Unplug,
  Satellite,
  Rss,
  Dice5,
  Handshake,
  Fish,
  Binoculars,
  Shell,
  Umbrella,
  LifeBuoy,
  Sun,
  Lamp,
  Projector,
  SlidersHorizontal,
} from 'lucide-react';
import type { AuthBrand } from '../services/auth';
import type { PageId } from '../types';

/** Marka süzgecinden muaf — her zaman göster (rol izinliyorsa) */
const ALWAYS_VISIBLE = new Set<PageId>([
  'hub',
  'brands',
  'guests',
  'notifications',
  'settings',
  'ops',
  'metrics',
  'reports',
  'webhooks',
  'docs',
  'incidents',
  'exports',
  'consent',
  'announcements',
  'audit',
  'brief',
  'readiness',
  'digest',
  'boardpack',
  'warroom',
  'nightly',
  'orbit',
  'apex',
  'pyramid',
  'signalhub',
  'skyline',
  'sentinel',
  'horizon',
  'meridian',
  'ledger',
  'peoplehub',
  'ecosphere',
  'brandpulse',
  'cognisphere',
  'vanguard',
  'lattice',
  'mirror',
  'keystone',
  'zenith',
  'odyssey',
  'tide',
  'harbor',
  'aurora',
]);

interface SidebarProps {
  active: PageId;
  allowedPages: string[];
  userName: string;
  userRole: string;
  brands?: AuthBrand[];
  activeBrandId?: string | null;
  onBrandChange?: (brandId: string) => void;
  onNavigate: (page: PageId) => void;
  onLogout: () => void;
}

const NAV_ITEMS: { id: PageId; label: string; description: string; icon: typeof Cpu }[] = [
  {
    id: 'komuta',
    label: 'LİKYA Komuta Merkezi',
    description: 'Sistem durumu & talimatlar',
    icon: LayoutDashboard,
  },
  {
    id: 'brief',
    label: 'Günlük Brief',
    description: 'Sabah operasyon özeti',
    icon: Sunrise,
  },
  {
    id: 'hub',
    label: 'Daze Hub',
    description: 'Merkezi operasyon özeti',
    icon: Network,
  },
  {
    id: 'ollama',
    label: 'Yerel AI (Ollama)',
    description: 'Model servisi & durum',
    icon: Cpu,
  },
  {
    id: 'ajanlar',
    label: 'IT & AI Ajanlar',
    description: '28 ajan · 9 departman',
    icon: Bot,
  },
  {
    id: 'olympospass',
    label: 'OlymposPass Geçiş',
    description: 'Kart/QR · kapı · NEXUS',
    icon: Ticket,
  },
  {
    id: 'field',
    label: 'Saha Modu',
    description: 'Tablet · offline kuyruk',
    icon: TabletSmartphone,
  },
  {
    id: 'chef',
    label: 'Daze Chef',
    description: 'Mutfak paneli & 2 dk kuralı',
    icon: ChefHat,
  },
  {
    id: 'crew',
    label: 'Daze Crew',
    description: 'Personel portalı & kazanç',
    icon: Users,
  },
  {
    id: 'vision',
    label: 'Daze Vision',
    description: 'Müşteri portalı & borsa',
    icon: HeartHandshake,
  },
  {
    id: 'nexus',
    label: 'NEXUS IoT',
    description: 'Turnike · kapı · RFID',
    icon: Radio,
  },
  {
    id: 'jobs',
    label: 'Görev Kuyruğu',
    description: 'Hatırlatma & talimat zamanlama',
    icon: ListTodo,
  },
  {
    id: 'venues',
    label: 'Tesisler',
    description: 'Çoklu locasyon & kapılar',
    icon: MapPin,
  },
  {
    id: 'brands',
    label: 'Markalar',
    description: 'Kiracı / ürün kapsamı',
    icon: Building2,
  },
  {
    id: 'guests',
    label: 'Misafir CRM',
    description: 'Pass · WA · geçiş izi',
    icon: UserRound,
  },
  {
    id: 'reports',
    label: 'Rapor & ETHOS',
    description: 'Operasyon özeti & uyum skoru',
    icon: ShieldCheck,
  },
  {
    id: 'notifications',
    label: 'Bildirimler',
    description: 'Operasyon gelen kutusu',
    icon: Bell,
  },
  {
    id: 'ops',
    label: 'Sistem & Yedek',
    description: 'Health · backup · restore',
    icon: HardDrive,
  },
  {
    id: 'metrics',
    label: 'Gözlemlenebilirlik',
    description: 'Metrikler & hata panosu',
    icon: BarChart3,
  },
  {
    id: 'inventory',
    label: 'Envanter',
    description: 'HEPHAESTUS stok & hareket',
    icon: Package,
  },
  {
    id: 'shifts',
    label: 'Vardiyalar',
    description: 'Crew vardiya planı',
    icon: CalendarClock,
  },
  {
    id: 'reservations',
    label: 'Rezervasyonlar',
    description: 'Masa / tesis planı',
    icon: CalendarCheck,
  },
  {
    id: 'loyalty',
    label: 'Sadakat',
    description: 'AURA · Daze-Gift puan',
    icon: Gift,
  },
  {
    id: 'incidents',
    label: 'Olay Panosu',
    description: 'Stok · görev · geçiş',
    icon: AlertTriangle,
  },
  {
    id: 'suppliers',
    label: 'Tedarik',
    description: 'AGORA satınalma',
    icon: Truck,
  },
  {
    id: 'feedback',
    label: 'Geri Bildirim',
    description: 'NPS & yorumlar',
    icon: MessageSquareHeart,
  },
  {
    id: 'exports',
    label: 'Dışa Aktarım',
    description: 'CSV katalog',
    icon: Download,
  },
  {
    id: 'consent',
    label: 'KVKK Onay',
    description: 'VALKYRIE onay günlüğü',
    icon: Scale,
  },
  {
    id: 'announcements',
    label: 'Duyurular',
    description: 'Holding brifing',
    icon: Megaphone,
  },
  {
    id: 'recipes',
    label: 'Reçeteler',
    description: 'Mutfak · stok düşüm',
    icon: UtensilsCrossed,
  },
  {
    id: 'checklists',
    label: 'Kontrol Listeleri',
    description: 'Açılış / kapanış',
    icon: ClipboardCheck,
  },
  {
    id: 'lostfound',
    label: 'Kayıp Eşya',
    description: 'Buluntu defteri',
    icon: Search,
  },
  {
    id: 'tips',
    label: 'Bahşiş Havuzu',
    description: 'Crew tip pool',
    icon: Coins,
  },
  {
    id: 'maintenance',
    label: 'Bakım',
    description: 'Arıza / ticket kuyruğu',
    icon: Wrench,
  },
  {
    id: 'menu',
    label: 'Menü',
    description: 'Fiyat & katalog',
    icon: Utensils,
  },
  {
    id: 'campaigns',
    label: 'Kampanyalar',
    description: 'Promo kodları',
    icon: BadgePercent,
  },
  {
    id: 'i18n',
    label: 'Lokalizasyon',
    description: 'BABEL çeviri notları',
    icon: Languages,
  },
  {
    id: 'coldchain',
    label: 'Soğuk Zincir',
    description: 'LOGOS sıcaklık log',
    icon: Thermometer,
  },
  {
    id: 'handover',
    label: 'Vardiya Teslim',
    description: 'Personel handover',
    icon: NotebookPen,
  },
  {
    id: 'cash',
    label: 'Kasa',
    description: 'Till hareketleri',
    icon: Wallet,
  },
  {
    id: 'assets',
    label: 'Varlıklar',
    description: 'Ekipman envanteri',
    icon: Boxes,
  },
  {
    id: 'energy',
    label: 'Enerji',
    description: 'Sayaç okumaları',
    icon: Zap,
  },
    { id: 'spa', label: 'Spa / Wellness', description: 'Spa randevu defteri.', icon: Sparkles },
  { id: 'eventcal', label: 'Etkinlikler', description: 'Tesis etkinlik takvimi.', icon: CalendarDays },
  { id: 'giftcards', label: 'Hediye Kartları', description: 'Daze-Gift bakiyeleri.', icon: CreditCard },
  { id: 'delivery', label: 'Paket Servis', description: 'Takeaway kuyruğu.', icon: Bike },
  { id: 'cleaning', label: 'Temizlik', description: 'Housekeeping görevleri.', icon: SprayCan },
  { id: 'laundry', label: 'Çamaşırhane', description: 'Tekstil partileri.', icon: Shirt },
  { id: 'wifi', label: 'WiFi Kupon', description: 'Misafir hotspot.', icon: Wifi },
  { id: 'content', label: 'İçerik Kuyruğu', description: 'Sosyal onay sırası.', icon: Images },
  { id: 'pulse', label: 'Ekip Nabız', description: 'Personel anketi.', icon: Activity },
  { id: 'budget', label: 'Bütçe', description: 'PLUTUS satırları.', icon: Landmark },
  { id: 'contracts', label: 'Sözleşmeler', description: 'Yenileme takibi.', icon: FileSignature },
  { id: 'passstock', label: 'Pass Stok', description: 'Kart/bileklik envanteri.', icon: ScanBarcode },
  { id: 'kds', label: 'KDS', description: 'Mutfak ekranı.', icon: MonitorPlay },
  { id: 'emergency', label: 'Acil Rehber', description: 'Acil iletişim.', icon: PhoneCall },
    { id: 'lockers', label: 'Dolap Kiralama', description: 'Spa/plaj dolapları.', icon: Lock },
  { id: 'kidsclub', label: 'Kids Club', description: 'Çocuk kulübü kayıt.', icon: Baby },
  { id: 'beachbeds', label: 'Şezlong', description: 'Sahil şezlong rezervasyonu.', icon: Palmtree },
  { id: 'transfers', label: 'Transfer Masası', description: 'Taksi / shuttle talepleri.', icon: Plane },
  { id: 'badgeprint', label: 'Kart Baskı', description: 'Pass yeniden baskı kuyruğu.', icon: Printer },
  { id: 'meetingrooms', label: 'Toplantı Odaları', description: 'Oda rezervasyonu.', icon: Presentation },
  { id: 'mediakit', label: 'Medya Kiti', description: 'Basın / içerik varlıkları.', icon: Clapperboard },
  { id: 'sustain', label: 'Sürdürülebilirlik', description: 'ESG metrik kayıtları.', icon: Leaf },
  { id: 'allergens', label: 'Alerjen Matrisi', description: 'Menü alerjen işaretleri.', icon: ShieldAlert },
  { id: 'winecellar', label: 'Şarap Mahzeni', description: 'Şarap stok/servis.', icon: Wine },
  { id: 'lounge', label: 'Lounge Log', description: 'Lounge ziyaret kaydı.', icon: Sofa },
  { id: 'shuttle', label: 'Shuttle Saatleri', description: 'Ring seferleri.', icon: Bus },
  { id: 'partners', label: 'Partner Oteller', description: 'B2B partner listesi.', icon: Hotel },
  { id: 'mysteryshop', label: 'Gizli Müşteri', description: 'Mystery shopper skorları.', icon: Eye },
  { id: 'concierge', label: 'Concierge', description: 'Misafir concierge talepleri.', icon: ConciergeBell },
  { id: 'minibar', label: 'Minibar', description: 'Oda minibar ikmal.', icon: Wine },
  { id: 'folio', label: 'Misafir Hesap', description: 'Folio charge post.', icon: Receipt },
  { id: 'banquet', label: 'Banket', description: 'Düğün / banket ops.', icon: PartyPopper },
  { id: 'tours', label: 'Tur Masası', description: 'Tur / gezi rezervasyonu.', icon: MapPinned },
  { id: 'marina', label: 'Marina', description: 'Tekne bağlama / slip.', icon: Anchor },
  { id: 'hammam', label: 'Hamam', description: 'Hamam randevu (spa dışı).', icon: Bath },
  { id: 'towels', label: 'Havlu Takibi', description: 'Plaj/havuz havlu stok.', icon: Shirt },
  { id: 'bands', label: 'Günlük Bileklik', description: 'Day-use bileklik dağıtım.', icon: Watch },
  { id: 'haccp', label: 'HACCP', description: 'Gıda güvenliği kayıtları.', icon: ClipboardList },
  { id: 'patrol', label: 'Güvenlik Turu', description: 'Gece/gündüz patrol log.', icon: Shield },
  { id: 'fleet', label: 'Araç Filosu', description: 'Transfer/vale araç durumu.', icon: Car },
  { id: 'payroll', label: 'Bordro Özeti', description: 'Haftalık bordro satırları.', icon: Banknote },
  { id: 'flash', label: 'Flash Rapor', description: 'Günlük doluluk / gelir satırı.', icon: Zap },
  { id: 'upsell', label: 'Upsell', description: 'Oda/deneyim yükseltme teklifleri.', icon: TrendingUp },
  { id: 'otareviews', label: 'OTA Yorumlar', description: 'Booking/Tripadvisor yanıt kuyruğu.', icon: MessageSquareQuote },
  { id: 'groups', label: 'Grup Rezervasyon', description: 'Grup / blok rezervasyon.', icon: UsersRound },
  { id: 'vipnotes', label: 'VIP Notları', description: 'VIP tercih / dikkat notları.', icon: Crown },
  { id: 'photoshoot', label: 'Fotoğraf Çekim', description: 'Profesyonel çekim randevuları.', icon: Camera },
  { id: 'dive', label: 'Dalış', description: 'Scuba / snorkeling aktivite.', icon: Waves },
  { id: 'bikerent', label: 'Bisiklet', description: 'Bisiklet kiralama.', icon: Bike },
  { id: 'cinema', label: 'Açık Hava Sinema', description: 'Sahil sinema seansları.', icon: Clapperboard },
  { id: 'retail', label: 'Butik', description: 'Butik / hediyelik satış.', icon: ShoppingBag },
  { id: 'bakery', label: 'Pastane', description: 'Pastane / özel sipariş.', icon: Croissant },
  { id: 'breakfast', label: 'Kahvaltı Slot', description: 'Kahvaltı rezervasyon slotları.', icon: Coffee },
  { id: 'lateout', label: 'Late Checkout', description: 'Geç çıkış talepleri.', icon: MoonStar },
  { id: 'amenities', label: 'Amenity', description: 'Oda amenity / ikram listesi.', icon: Gift },
  { id: 'nightlog', label: 'Gece Log', description: 'Night audit operasyon satırları.', icon: ClipboardCheck },
  { id: 'keycards', label: 'Oda Kartı', description: 'Kapı kartı programlama kuyruğu.', icon: KeyRound },
  { id: 'roomstatus', label: 'Oda Durumu', description: 'HK oda durum panosu.', icon: DoorOpen },
  { id: 'bedding', label: 'Yatak / Extra', description: 'Ekstra yatak / beşik talepleri.', icon: BedDouble },
  { id: 'wakeups', label: 'Wake-up', description: 'Uyandırma çağrıları.', icon: AlarmClock },
  { id: 'parcels', label: 'Kargo / Emanet', description: 'Misafir kargo ve emanet.', icon: PackageCheck },
  { id: 'qrcheckin', label: 'QR Check-in', description: 'Mobil QR check-in oturumları.', icon: QrCode },
  { id: 'guestapp', label: 'Misafir App', description: 'Push / in-app bildirim kuyruğu.', icon: Smartphone },
  { id: 'karaoke', label: 'Karaoke', description: 'Eğlence / karaoke rezervasyon.', icon: Mic2 },
  { id: 'artwall', label: 'Sanat Duvarı', description: 'Galeri / sanat eser envanteri.', icon: Palette },
  { id: 'florals', label: 'Çiçek', description: 'Oda / etkinlik çiçek siparişi.', icon: Flower2 },
  { id: 'privatechef', label: 'Özel Şef', description: 'Private chef deneyimleri.', icon: ChefHat },
  { id: 'mocktails', label: 'Mocktail Bar', description: 'Alkolsüz imza içecekler.', icon: GlassWater },
  { id: 'promos', label: 'Promo Kod', description: 'Promosyon kod envanteri.', icon: TicketPercent },
  { id: 'dawnservice', label: 'Şafak Servisi', description: 'Erken kahve / gazete turu.', icon: Sunrise },
  { id: 'rosters', label: 'Haftalık Roster', description: 'Personel haftalık plan.', icon: CalendarRange },
  { id: 'overtime', label: 'Mesai', description: 'Fazla mesai talepleri.', icon: Timer },
  { id: 'uniforms', label: 'Üniforma', description: 'Üniforma zimmet / stok.', icon: Shirt },
  { id: 'healthcards', label: 'Sağlık Kartı', description: 'Personel sağlık / hijyen kartı.', icon: HeartPulse },
  { id: 'visitors', label: 'Ziyaretçi', description: 'Tesis ziyaretçi kayıt.', icon: IdCard },
  { id: 'cctvlog', label: 'CCTV Log', description: 'Kamera olay notları.', icon: Cctv },
  { id: 'firedrill', label: 'Yangın Tatbikat', description: 'Tatbikat kayıtları.', icon: Flame },
  { id: 'insurance', label: 'Sigorta', description: 'Poliçe yenileme takibi.', icon: ShieldPlus },
  { id: 'invoices', label: 'Fatura', description: 'Alacak / borç fatura satırları.', icon: FileSpreadsheet },
  { id: 'taxpack', label: 'Vergi Paketi', description: 'Vergi dönem satırları.', icon: Calculator },
  { id: 'forecast', label: 'Gelir Forecast', description: 'Haftalık gelir tahmini.', icon: LineChart },
  { id: 'capex', label: 'CAPEX', description: 'Yatırım talepleri.', icon: Building },
  { id: 'licenses', label: 'Ruhsat', description: 'İşletme ruhsat / izin.', icon: Stamp },
  { id: 'slabreaches', label: 'SLA İhlal', description: 'Tedarik / servis SLA ihlalleri.', icon: TriangleAlert },
  { id: 'extlinks', label: 'Entegrasyonlar', description: 'Harici sistem bağlantı durumu.', icon: PlugZap },
  { id: 'apikeys', label: 'API Anahtar', description: 'Servis API key envanteri.', icon: KeySquare },
  { id: 'backupsched', label: 'Yedek Zamanla', description: 'Backup schedule kayıtları.', icon: DatabaseBackup },
  { id: 'sysalerts', label: 'Sistem Alarm', description: 'Altyapı alarm kuyruğu.', icon: ServerCrash },
  { id: 'bugtracker', label: 'Bug Tracker', description: 'İç yazılım hata kayıtları.', icon: Bug },
  { id: 'releasenotes', label: 'Release Notes', description: 'Sürüm notları.', icon: GitBranch },
  { id: 'runbooks', label: 'Runbook', description: 'Operasyon runbook listesi.', icon: Terminal },
  { id: 'biometrics', label: 'Biyometrik', description: 'Biyometrik erişim log.', icon: Fingerprint },
  { id: 'secretsrot', label: 'Secret Rotation', description: 'Secret döndürme planı.', icon: KeyRound },
  { id: 'dnscheck', label: 'DNS Check', description: 'Domain / DNS sağlık.', icon: Globe2 },
  { id: 'mailqueue', label: 'Mail Kuyruk', description: 'E-posta gönderim kuyruğu.', icon: Mail },
  { id: 'smsqueue', label: 'SMS Kuyruk', description: 'SMS gönderim kuyruğu.', icon: MessageCircle },
  { id: 'alertrules', label: 'Alert Kuralları', description: 'Bildirim kural tanımı.', icon: BellRing },
  { id: 'edgecache', label: 'Edge Cache', description: 'CDN / edge cache durum.', icon: CloudFog },
  { id: 'signage', label: 'Dijital Tabela', description: 'Ekran içerik kuyruğu.', icon: MonitorPlay },
  { id: 'wayfind', label: 'Wayfinding', description: 'Yönlendirme noktaları.', icon: MapPinned },
  { id: 'beaconmap', label: 'Beacon Harita', description: 'BLE beacon yerleşimi.', icon: Radio },
  { id: 'iotgates', label: 'IoT Kapı', description: 'Kapı sensör log.', icon: DoorOpen },
  { id: 'powerops', label: 'Güç Ops', description: 'Jeneratör / UPS durumu.', icon: Zap },
  { id: 'waterops', label: 'Su Ops', description: 'Su tank / sayaç.', icon: GlassWater },
  { id: 'greenops', label: 'Yeşil Ops', description: 'Yeşil alan bakım.', icon: Leaf },
  { id: 'pestctrl', label: 'Haşere', description: 'Haşere kontrol turları.', icon: Bug },
  { id: 'chemlog', label: 'Kimyasal Log', description: 'Havuz kimyasal dozaj.', icon: FlaskConical },
  { id: 'poolops', label: 'Havuz Ops', description: 'Havuz parametreleri.', icon: Waves },
  { id: 'saunaops', label: 'Sauna', description: 'Sauna oturum / ısı.', icon: Flame },
  { id: 'steamops', label: 'Steam', description: 'Buhar odası durumu.', icon: CloudFog },
  { id: 'icebath', label: 'Buz Banyo', description: 'Ice bath rezervasyon.', icon: Snowflake },
  { id: 'recovslots', label: 'Recovery Slot', description: 'Spor recovery randevu.', icon: HeartPulse },
  { id: 'helipad', label: 'Helipad', description: 'Helikopter iniş slotları.', icon: PlaneTakeoff },
  { id: 'jetski', label: 'Jet Ski', description: 'Jet ski kiralama.', icon: Ship },
  { id: 'yacht', label: 'Yat Charter', description: 'Yat / tekne charter.', icon: Sailboat },
  { id: 'surfschool', label: 'Surf School', description: 'Sörf ders rezervasyonu.', icon: Wind },
  { id: 'paddle', label: 'Paddle', description: 'SUP / paddle board.', icon: Waves },
  { id: 'climwall', label: 'Tırmanma', description: 'Tırmanma duvarı slot.', icon: BrickWall },
  { id: 'escaperoom', label: 'Escape Room', description: 'Escape room seansları.', icon: DoorClosed },
  { id: 'arcade', label: 'Arcade', description: 'Oyun salonu / kredi.', icon: Joystick },
  { id: 'bowling', label: 'Bowling', description: 'Bowling kulvar rezervasyon.', icon: Target },
  { id: 'billiards', label: 'Bilardo', description: 'Bilardo masa rezervasyon.', icon: CircleDot },
  { id: 'pokertable', label: 'Poker', description: 'Özel poker masa / turnuva.', icon: Spade },
  { id: 'trivia', label: 'Trivia', description: 'Trivia gece yarışmaları.', icon: HelpCircle },
  { id: 'djbooth', label: 'DJ Booth', description: 'DJ set / sahne planı.', icon: Disc3 },
  { id: 'soundcheck', label: 'Soundcheck', description: 'Sahne ses kontrol listesi.', icon: AudioLines },
  { id: 'crowddens', label: 'Yoğunluk', description: 'Bölge kalabalık yoğunluğu.', icon: Users },
  { id: 'queuetimes', label: 'Kuyruk Süresi', description: 'Servis noktası bekleme.', icon: Timer },
  { id: 'lostchild', label: 'Kayıp Çocuk', description: 'Kayıp çocuk protokol log.', icon: Baby },
  { id: 'firstaid', label: 'İlk Yardım', description: 'İlk yardım müdahale kaydı.', icon: HeartPulse },
  { id: 'aedcheck', label: 'AED Kontrol', description: 'AED cihaz kontrol listesi.', icon: ShieldPlus },
  { id: 'evacdrill', label: 'Tahliye Tatbikat', description: 'Tahliye tatbikat kaydı.', icon: Siren },
  { id: 'crowdctrl', label: 'Kalabalık Kontrol', description: 'Crowd control görevleri.', icon: Shield },
  { id: 'radiolog', label: 'Telsiz Log', description: 'Telsiz kanal olayları.', icon: Radio },
  { id: 'gatequeue', label: 'Gate Kuyruk', description: 'Pass gate bekleme.', icon: ScanBarcode },
  { id: 'wristscan', label: 'Bileklik Scan', description: 'Bileklik okuma log.', icon: Watch },
  { id: 'facepass', label: 'Face Pass', description: 'Yüz tanıma geçiş denemesi.', icon: ScanFace },
  { id: 'bagcheck', label: 'Çanta Kontrol', description: 'Güvenlik çanta kontrol.', icon: Briefcase },
  { id: 'metaldet', label: 'Metal Dedektör', description: 'Metal dedektör olayları.', icon: ScanLine },
  { id: 'watchlist', label: 'İzleme Listesi', description: 'Güvenlik izleme listesi.', icon: Eye },
  { id: 'menuboard', label: 'Menü Board', description: 'Dijital menü panosu yayın.', icon: MonitorPlay },
  { id: 'allergenalert', label: 'Alerjen Alarm', description: 'Mutfak alerjen uyarıları.', icon: ShieldAlert },
  { id: 'tempprobe', label: 'Sıcaklık Probe', description: 'Gıda sıcaklık ölçüm.', icon: Thermometer },
  { id: 'prepqueue', label: 'Prep Kuyruk', description: 'Hazırlık / mise en place.', icon: UtensilsCrossed },
  { id: 'voidlog', label: 'Void Log', description: 'POS iptal / void kayıt.', icon: Ban },
  { id: 'comps', label: 'Comp', description: 'İkram / comp onayları.', icon: Gift },
  { id: 'splitbill', label: 'Hesap Böl', description: 'Split bill talepleri.', icon: Split },
  { id: 'tabopen', label: 'Açık Tab', description: 'Açık hesap / tab listesi.', icon: Receipt },
  { id: 'corkage', label: 'Corkage', description: 'Şişe açma ücreti kayıt.', icon: Wine },
  { id: 'sommelier', label: 'Sommelier', description: 'Şarap öneri / pairing.', icon: GlassWater },
  { id: 'chefnote', label: 'Şef Notu', description: 'Günlük şef brifi notları.', icon: NotebookPen },
  { id: 'passticket', label: 'Pass Ticket', description: 'Pass desk hızlı bilet.', icon: Ticket },
  { id: 'zoneheat', label: 'Zone Heat', description: 'Bölge ısı haritası satırı.', icon: Flame },
  { id: 'revpulse', label: 'Rev Pulse', description: 'Anlık gelir nabız satırı.', icon: LineChart },
  { id: 'stayext', label: 'Konaklama Uzat', description: 'Stay extension teklifleri.', icon: CalendarClock },
  { id: 'roommove', label: 'Oda Taşıma', description: 'Room move talepleri.', icon: DoorOpen },
  { id: 'earlyin', label: 'Erken Check-in', description: 'Early check-in kuyruğu.', icon: AlarmClock },
  { id: 'luggage', label: 'Bagaj', description: 'Bagaj emanet / taşıma.', icon: Briefcase },
  { id: 'turndown', label: 'Turndown', description: 'Akşam turndown servisi.', icon: MoonStar },
  { id: 'pillowmenu', label: 'Yastık Menü', description: 'Yastık tercihleri.', icon: BedDouble },
  { id: 'scenting', label: 'Oda Kokusu', description: 'Oda scenting tercihleri.', icon: Flower2 },
  { id: 'dndflags', label: 'DND / MUR', description: 'DND ve Make Up Room bayrakları.', icon: DoorClosed },
  { id: 'bathstock', label: 'Bornoz Stok', description: 'Bornoz / terlik zimmet.', icon: Shirt },
  { id: 'ironreq', label: 'Ütü Talebi', description: 'Ütü / board talepleri.', icon: Zap },
  { id: 'pressing', label: 'Pressing', description: 'Kuru temizleme / pressing.', icon: Sparkles },
  { id: 'shoeshine', label: 'Ayakkabı Boya', description: 'Shoe shine servisi.', icon: Footprints },
  { id: 'babycot', label: 'Bebek Karyola', description: 'Baby cot / beşik talepleri.', icon: Baby },
  { id: 'petstay', label: 'Pet Stay', description: 'Evcil hayvan konak kayıt.', icon: PawPrint },
  { id: 'arbill', label: 'AR Fatura', description: 'Alacak yaşlandırma satırları.', icon: ReceiptText },
  { id: 'apbill', label: 'AP Ödeme', description: 'Borç ödeme kuyruğu.', icon: WalletCards },
  { id: 'bankrec', label: 'Banka Mutabakat', description: 'Hesap mutabakat satırları.', icon: Landmark },
  { id: 'fxrates', label: 'Döviz Kur', description: 'Günlük FX kurları.', icon: BadgeDollarSign },
  { id: 'tipout', label: 'Tip Out', description: 'Bahşiş dağıtım satırları.', icon: Coins },
  { id: 'deposit', label: 'Depozito', description: 'Misafir depozito kayıtları.', icon: PiggyBank },
  { id: 'refunds', label: 'İade', description: 'Ödeme iade kuyruğu.', icon: TrendingDown },
  { id: 'chargeback', label: 'Chargeback', description: 'Kart chargeback dosyaları.', icon: Scale },
  { id: 'giftred', label: 'Hediye Kullanım', description: 'Gift card redeem log.', icon: Gift },
  { id: 'memberbill', label: 'Üyelik Fatura', description: 'Pass üyelik faturaları.', icon: CreditCard },
  { id: 'rateplan', label: 'Rate Plan', description: 'Oda/pass rate planları.', icon: Percent },
  { id: 'channelmgr', label: 'Channel Manager', description: 'OTA kanal eşlemeleri.', icon: Globe },
  { id: 'overbook', label: 'Overbooking', description: 'Overbooking karar kayıtları.', icon: Layers },
  { id: 'yieldrule', label: 'Yield Kural', description: 'Dinamik fiyat kuralları.', icon: TrendingUp },
  { id: 'onboarding', label: 'Onboarding', description: 'Yeni personel giriş checklist.', icon: UserRound },
  { id: 'offboarding', label: 'Offboarding', description: 'İşten ayrılış checklist.', icon: LogOut },
  { id: 'interviews', label: 'Mülakat', description: 'Aday mülakat takvimi.', icon: UsersRound },
  { id: 'certifications', label: 'Sertifika', description: 'Personel sertifika kaydı.', icon: Award },
  { id: 'langskill', label: 'Dil Yetkinlik', description: 'Personel dil seviyeleri.', icon: Languages },
  { id: 'shiftswap', label: 'Vardiya Takas', description: 'Shift swap talepleri.', icon: ArrowLeftRight },
  { id: 'leaverequest', label: 'İzin Talebi', description: 'Yıllık / mazeret izin.', icon: CalendarRange },
  { id: 'attendance', label: 'Yoklama', description: 'Günlük yoklama satırları.', icon: ClipboardCheck },
  { id: 'performance', label: 'Performans', description: 'Performans notları.', icon: Star },
  { id: 'recognition', label: 'Ödül', description: 'Resmi takdir / ödül.', icon: Trophy },
  { id: 'handbook', label: 'El Kitabı', description: 'Handbook okuma onayı.', icon: BookOpen },
  { id: 'safetybrief', label: 'İSG Brifi', description: 'İş güvenliği brifing.', icon: HardHat },
  { id: 'nearmiss', label: 'Near Miss', description: 'Ramak kala olay raporları.', icon: TriangleAlert },
  { id: 'whistle', label: 'Bildirim Hattı', description: 'Anonim etik bildirim.', icon: Megaphone },
  { id: 'carbonlog', label: 'Karbon Log', description: 'Karbon ayak izi kayıtları.', icon: Factory },
  { id: 'wateraudit', label: 'Su Denetim', description: 'Su tüketim denetim satırları.', icon: Droplets },
  { id: 'airquality', label: 'Hava Kalite', description: 'İç ortam hava kalitesi.', icon: Fan },
  { id: 'solarops', label: 'Güneş Enerji', description: 'Solar üretim / durum.', icon: SunMedium },
  { id: 'biodiversity', label: 'Biyoçeşitlilik', description: 'Yerel flora/fauna gözlem.', icon: TreeDeciduous },
  { id: 'recycling', label: 'Geri Dönüşüm', description: 'Geri dönüşüm tonaj kayıt.', icon: Recycle },
  { id: 'greencert', label: 'Yeşil Sertifika', description: 'Çevre sertifika takibi.', icon: BadgeCheck },
  { id: 'auditfind', label: 'Denetim Bulgu', description: 'İç/dış denetim bulguları.', icon: ClipboardList },
  { id: 'policyack', label: 'Politika Onay', description: 'Politika okuma onayları.', icon: FileCheck2 },
  { id: 'dataprotect', label: 'Veri Koruma', description: 'KVKK işlem kayıtları.', icon: ShieldCheck },
  { id: 'retention', label: 'Saklama Politikası', description: 'Veri saklama süre satırları.', icon: ScrollText },
  { id: 'accessreview', label: 'Erişim Gözden Geçir', description: 'Rol/erişim periyodik review.', icon: KeyRound },
  { id: 'vendorrisk', label: 'Tedarik Risk', description: 'Vendor risk skorları.', icon: TriangleAlert },
  { id: 'legalhold', label: 'Legal Hold', description: 'Hukuki saklama emirleri.', icon: Gavel },
  { id: 'presskit', label: 'Basın Kiti', description: 'Basın varlık / kit listesi.', icon: Newspaper },
  { id: 'influencer', label: 'Influencer', description: 'Influencer işbirlikleri.', icon: Share2 },
  { id: 'ugcmod', label: 'UGC Moderasyon', description: 'Kullanıcı içerik onay.', icon: Images },
  { id: 'seoaudit', label: 'SEO Denetim', description: 'SEO bulgu satırları.', icon: Search },
  { id: 'adspend', label: 'Reklam Harcama', description: 'Medya harcama satırları.', icon: BadgePercent },
  { id: 'brandguard', label: 'Marka Koruma', description: 'Marka ihlal / taklit izleme.', icon: ShieldCheck },
  { id: 'storyboard', label: 'Storyboard', description: 'İçerik storyboard panosu.', icon: Clapperboard },
  { id: 'livestream', label: 'Canlı Yayın', description: 'Livestream plan / durum.', icon: Video },
  { id: 'podcastshow', label: 'Podcast', description: 'Podcast bölüm planı.', icon: Podcast },
  { id: 'newsletter', label: 'Bülten', description: 'E-posta bülten kuyruğu.', icon: Mail },
  { id: 'tagmap', label: 'Hashtag Harita', description: 'Kampanya hashtag eşlemi.', icon: Hash },
  { id: 'socialinbox', label: 'Sosyal Inbox', description: 'Sosyal mesaj / DM kuyruğu.', icon: MessageSquareHeart },
  { id: 'mediaembargo', label: 'Embargo', description: 'Medya embargo takvimi.', icon: Clock3 },
  { id: 'creativereq', label: 'Kreatif Talep', description: 'ARTE / kreatif brief kuyruğu.', icon: PenLine },
  { id: 'modelops', label: 'Model Ops', description: 'Model deploy / sürüm.', icon: Cpu },
  { id: 'promptlib', label: 'Prompt Lib', description: 'Prompt şablon kütüphanesi.', icon: NotebookPen },
  { id: 'agenteval', label: 'Ajan Eval', description: 'Ajan kalite skorları.', icon: Bot },
  { id: 'tokenbudget', label: 'Token Bütçe', description: 'Ajan token limitleri.', icon: Gauge },
  { id: 'ragindex', label: 'RAG Index', description: 'Bilgi bankası index işleri.', icon: DatabaseBackup },
  { id: 'toolpermit', label: 'Tool İzin', description: 'Ajan tool izin matrisi.', icon: KeySquare },
  { id: 'sandboxrun', label: 'Sandbox Run', description: 'Güvenli ajan deneme koşuları.', icon: Terminal },
  { id: 'hallucheck', label: 'Hallucination Check', description: 'Halüsinasyon denetim satırları.', icon: Eye },
  { id: 'datasetcur', label: 'Dataset Kürasyon', description: 'Eğitim / eval veri setleri.', icon: Boxes },
  { id: 'redteam', label: 'Red Team', description: 'AI red-team testleri.', icon: Swords },
  { id: 'slaagent', label: 'Ajan SLA', description: 'Ajan yanıt SLA kayıtları.', icon: Timer },
  { id: 'costguard', label: 'AI Cost Guard', description: 'AI maliyet koruma alarmları.', icon: Wallet },
  { id: 'latencylog', label: 'Latency Log', description: 'Model latency örnekleri.', icon: Activity },
  { id: 'driftmonitor', label: 'Drift Monitor', description: 'Model drift izleme.', icon: LineChart },
    { id: 'posbridge', label: 'POS Bridge', description: 'Mağaza içi otonom ödeme köprüsü.', icon: Store },
  { id: 'dynamint', label: 'MINT Fiyat Push', description: 'Dinamik borsa fiyatının satış noktasına aktarımı.', icon: CandlestickChart },
  { id: 'couriertrack', label: 'Kurye Takip', description: 'Kurye / lojistik canlı konum satırları.', icon: Truck },
  { id: 'autocheckout', label: 'Otonom Checkout', description: 'Scan & go / otonom kasa oturumları.', icon: ScanBarcode },
  { id: 'loyaltyburn', label: 'Sadakat Harcama', description: 'Puan / tier burn işlemleri.', icon: Coins },
  { id: 'treatoffer', label: 'İkram Teklifi', description: 'Misafir ikram / treat mekanizması.', icon: Sparkles },
  { id: 'omnimarket', label: 'Omni Market', description: 'Omni-kanal ürün / listing panosu.', icon: ShoppingBag },
  { id: 'clickcollect', label: 'Click & Collect', description: 'Online al · yerinde teslim.', icon: PackageCheck },
  { id: 'lastmile', label: 'Last Mile', description: 'Son mil teslimat görevleri.', icon: Route },
  { id: 'invsync', label: 'Stok Senkron', description: 'Kanal stok senkron işleri.', icon: RefreshCw },
  { id: 'pricepush', label: 'Fiyat Push', description: 'Fiyat güncellemesinin POS/app yayını.', icon: Tags },
  { id: 'qrpay', label: 'QR Pay', description: 'QR ödeme oturumları.', icon: QrCode },
  { id: 'courierpool', label: 'Kurye Havuzu', description: 'Aktif kurye kapasitesi.', icon: Bike },
  { id: 'giftrelay', label: 'Hediye Relay', description: 'İkram / hediye zincir teslimatı.', icon: Gift },
    { id: 'edgegate', label: 'Edge Gate', description: 'Kenar ağ geçidi durumu.', icon: Router },
  { id: 'meshlink', label: 'Mesh Link', description: 'Mesh düğüm bağlantıları.', icon: Network },
  { id: 'radiomesh', label: 'Radio Mesh', description: 'Radyo mesh kanal sağlığı.', icon: RadioTower },
  { id: 'sensorfuse', label: 'Sensor Fuse', description: 'Sensör füzyon olayları.', icon: Antenna },
  { id: 'otafirm', label: 'OTA Firmware', description: 'Cihaz OTA firmware kuyruğu.', icon: CloudUpload },
  { id: 'devinventory', label: 'Cihaz Envanter', description: 'IoT cihaz envanter satırları.', icon: HardDrive },
  { id: 'powerbudget', label: 'Güç Bütçe', description: 'Edge güç bütçe limitleri.', icon: Zap },
  { id: 'backhaul', label: 'Backhaul', description: 'Backhaul hat durumu.', icon: Cable },
  { id: 'edgecache2', label: 'Edge Store', description: 'Kenar önbellek / store durumu.', icon: DatabaseBackup },
  { id: 'syncrepl', label: 'Sync Replica', description: 'Edge→cloud sync replica.', icon: CloudDownload },
  { id: 'failover', label: 'Failover', description: 'Edge failover olayları.', icon: Unplug },
  { id: 'telemetry', label: 'Telemetry', description: 'Telemetry örnek satırları.', icon: Activity },
  { id: 'netslice', label: 'Net Slice', description: 'Ağ dilimi / QoS tanımları.', icon: Layers },
  { id: 'satlink', label: 'Sat Link', description: 'Yedek uydu bağlantısı.', icon: Satellite },
    { id: 'guesttwin', label: 'Guest Twin', description: 'Misafir dijital ikiz profili.', icon: UserRound },
  { id: 'prefgraph', label: 'Tercih Grafı', description: 'Tercih ilişki düğümleri.', icon: Share2 },
  { id: 'intentscore', label: 'Niyet Skoru', description: 'Satın alma / deneyim niyet skoru.', icon: Gauge },
  { id: 'nextbest', label: 'Next Best Action', description: 'Sonraki en iyi aksiyon önerisi.', icon: Sparkles },
  { id: 'journeymap', label: 'Yolculuk Haritası', description: 'Misafir journey adımları.', icon: MapPinned },
  { id: 'microseg', label: 'Mikro Segment', description: 'Dinamik mikro segmentler.', icon: Users },
  { id: 'offerlab', label: 'Offer Lab', description: 'Teklif deney / A-B lab.', icon: FlaskConical },
  { id: 'consentgraph', label: 'Consent Graph', description: 'İzin / kanal onay grafı.', icon: ShieldCheck },
  { id: 'emotionpulse', label: 'Duygu Nabız', description: 'Anlık duygu / memnuniyet nabzı.', icon: HeartHandshake },
  { id: 'servicememory', label: 'Servis Hafızası', description: 'Servis ekibi hafıza notları.', icon: NotebookPen },
  { id: 'recoverypath', label: 'Recovery Path', description: 'Hizmet kurtarma yolları.', icon: HeartPulse },
  { id: 'lifetimeval', label: 'LTV', description: 'Ömür boyu değer tahmini.', icon: BadgeDollarSign },
  { id: 'churnrisk', label: 'Churn Risk', description: 'Ayrılma / dönmeme riski.', icon: TrendingDown },
  { id: 'wowmoment', label: 'Wow Moment', description: 'Sürpriz / wow anı planı.', icon: PartyPopper },
    { id: 'incidentbus', label: 'Incident Bus', description: 'Olay veri yolu mesajları.', icon: Rss },
  { id: 'playtrigger', label: 'Play Trigger', description: 'Playbook tetikleyicileri.', icon: Zap },
  { id: 'escalation', label: 'Escalation', description: 'Yükseltme matrisi kayıtları.', icon: TriangleAlert },
  { id: 'warroomseat', label: 'War Room Seat', description: 'War room koltuk / rol ataması.', icon: Armchair },
  { id: 'decisionlog', label: 'Decision Log', description: 'Karar günlüğü.', icon: ScrollText },
  { id: 'slotrack', label: 'SLO Track', description: 'Servis seviyesi hedef takibi.', icon: Target },
  { id: 'errorbudget', label: 'Error Budget', description: 'Hata bütçesi tüketimi.', icon: Percent },
  { id: 'changewindow', label: 'Change Window', description: 'Değişiklik penceresi planı.', icon: CalendarClock },
  { id: 'blameless', label: 'Blameless Review', description: 'Blameless postmortem kayıtları.', icon: FileText },
  { id: 'pagerduty', label: 'On-Call', description: 'Nöbet / on-call rotası.', icon: PhoneCall },
  { id: 'statuspage', label: 'Status Page', description: 'Dış durum sayfası bileşenleri.', icon: MonitorPlay },
  { id: 'runbooklink', label: 'Runbook Link', description: 'Olay→runbook eşlemesi.', icon: BookOpen },
  { id: 'commsbridge', label: 'Comms Bridge', description: 'Kriz iletişim köprüsü.', icon: Megaphone },
  { id: 'afteraction', label: 'After Action', description: 'After-action madde listesi.', icon: ClipboardCheck },
    { id: 'revstream', label: 'Gelir Akışı', description: 'Kanal bazlı gelir akış satırları.', icon: LineChart },
  { id: 'packagemix', label: 'Paket Mix', description: 'Paket / bundle karışımı.', icon: Boxes },
  { id: 'ancillary', label: 'Ancillary', description: 'Ek satış / ancillary gelir.', icon: ShoppingBag },
  { id: 'dynamicbundle', label: 'Dinamik Bundle', description: 'Dinamik paket önerileri.', icon: Tags },
  { id: 'pricefloor', label: 'Fiyat Tabanı', description: 'Minimum fiyat kuralları.', icon: TrendingDown },
  { id: 'compset', label: 'Comp Set', description: 'Rakip / compset fiyat izleme.', icon: Eye },
  { id: 'pickuppace', label: 'Pickup Pace', description: 'Rezervasyon pickup temposu.', icon: Gauge },
  { id: 'noshowrisk', label: 'No-show Risk', description: 'No-show risk skorları.', icon: AlertTriangle },
  { id: 'walkinflow', label: 'Walk-in Flow', description: 'Walk-in talep akışı.', icon: Users },
  { id: 'tableturn', label: 'Table Turn', description: 'Masa dönüş hızı kayıtları.', icon: Timer },
  { id: 'beatrevenue', label: 'Beat Revenue', description: 'Beat / hedef karşılaştırma.', icon: TrendingUp },
  { id: 'cashforecast', label: 'Nakit Forecast', description: 'Kısa vadeli nakit tahmini.', icon: Wallet },
  { id: 'marginwatch', label: 'Marj İzleme', description: 'Ürün / kanal marj izleme.', icon: Percent },
  { id: 'promoattr', label: 'Promo Attribution', description: 'Promosyon atıf satırları.', icon: BadgePercent },
    { id: 'masterplan', label: 'Master Plan', description: 'Holding master plan maddeleri.', icon: MapPinned },
  { id: 'okrrack', label: 'OKR Rack', description: 'OKR / hedef rafları.', icon: Target },
  { id: 'roadmap', label: 'Roadmap', description: 'Ürün / tesis roadmap satırları.', icon: ListTodo },
  { id: 'betboard', label: 'Bet Board', description: 'Stratejik bet panosu.', icon: Dice5 },
  { id: 'portfoliorisk', label: 'Portföy Risk', description: 'Holding portföy risk satırları.', icon: Scale },
  { id: 'captable', label: 'Cap Notes', description: 'Sermaye / ortaklık notları.', icon: FileSpreadsheet },
  { id: 'boardmotion', label: 'Board Motion', description: 'Yönetim kurulu karar taslakları.', icon: Gavel },
  { id: 'alliance', label: 'Alliance', description: 'Stratejik ittifak kayıtları.', icon: Handshake },
  { id: 'expansion', label: 'Expansion', description: 'Yeni tesis / şehir genişleme.', icon: Globe },
  { id: 'legacyarc', label: 'Legacy Arc', description: 'Uzun vadeli miras / legacy ark.', icon: Landmark },
  { id: 'culturecode', label: 'Culture Code', description: 'Kültür kodu maddeleri.', icon: HeartHandshake },
  { id: 'talentbet', label: 'Talent Bet', description: 'Yetenek yatırımı bahisleri.', icon: GraduationCap },
  { id: 'moatwatch', label: 'Moat Watch', description: 'Rekabet hendek / moat izleme.', icon: Shield },
  { id: 'northstar', label: 'North Star', description: 'Kuzey yıldızı metrik satırları.', icon: Sparkles },
    { id: 'tidewatch', label: 'Gelgit İzleme', description: 'Gelgit / su seviyesi gözlemi.', icon: Waves },
  { id: 'duneops', label: 'Kumsal Ops', description: 'Kumsal / dune bakım görevleri.', icon: Palmtree },
  { id: 'snorkelbay', label: 'Snorkel Bay', description: 'Snorkel koyu aktivite slotları.', icon: Fish },
  { id: 'cliffpath', label: 'Uçurum Yolu', description: 'Likya yolu / cliff path durumu.', icon: Mountain },
  { id: 'campglow', label: 'Camp Glow', description: 'Sahil kamp / ateş alanı.', icon: Flame },
  { id: 'lookout', label: 'Lookout', description: 'Manzara / lookout noktaları.', icon: Binoculars },
  { id: 'reefguard', label: 'Reef Guard', description: 'Resif koruma gözlemleri.', icon: Shell },
  { id: 'pierops', label: 'İskele Ops', description: 'İskele operasyon kayıtları.', icon: Anchor },
  { id: 'saildesk', label: 'Yelken Desk', description: 'Yelken / tekne desk rezervasyon.', icon: Ship },
  { id: 'umbrellamap', label: 'Şemsiye Harita', description: 'Şemsiye / kabin yerleşimi.', icon: Umbrella },
  { id: 'sandclean', label: 'Kum Temizlik', description: 'Kumsal temizlik turları.', icon: Wind },
  { id: 'nightswim', label: 'Gece Yüzme', description: 'Gece yüzme izin / slot.', icon: MoonStar },
  { id: 'stargaze', label: 'Yıldız İzleme', description: 'Stargazing etkinlik slotları.', icon: Sparkles },
  { id: 'coastpatrol', label: 'Sahil Devriye', description: 'Sahil güvenlik / cankurtaran turu.', icon: LifeBuoy },
    { id: 'harborlane', label: 'Liman Şeridi', description: 'Liman yaklaşma şeritleri.', icon: Route },
  { id: 'dockslot', label: 'Rıhtım Slot', description: 'Rıhtım bağlama slotları.', icon: Anchor },
  { id: 'craneops', label: 'Vinç Ops', description: 'Vinç / kaldırma operasyonları.', icon: Factory },
  { id: 'container', label: 'Konteyner', description: 'Konteyner hareket kayıtları.', icon: Boxes },
  { id: 'coldbay', label: 'Soğuk Bay', description: 'Soğuk zincir bay / depo.', icon: Thermometer },
  { id: 'yardmove', label: 'Saha Hamle', description: 'Yard içi taşıma görevleri.', icon: Truck },
  { id: 'gatepass', label: 'Liman Gate', description: 'Liman kapı geçiş fişleri.', icon: Ticket },
  { id: 'bolthold', label: 'Bolt Hold', description: 'Güvenlik / hold işaretleri.', icon: Lock },
  { id: 'manifest', label: 'Manifest', description: 'Yük manifesto satırları.', icon: ClipboardList },
  { id: 'demurrage', label: 'Demurrage', description: 'Demurrage / bekletme ücretleri.', icon: Timer },
  { id: 'pilotage', label: 'Kılavuzluk', description: 'Pilot / kılavuz talepleri.', icon: Compass },
  { id: 'tugassist', label: 'Römorkör', description: 'Römorkör asistansı.', icon: Ship },
  { id: 'wharfage', label: 'Wharfage', description: 'Rıhtım kullanım ücretleri.', icon: Coins },
  { id: 'stevedore', label: 'Stevedore', description: 'Yükleme ekibi / vardiya.', icon: Users },
    { id: 'auroradeck', label: 'Aurora Deck', description: 'Deneyim güverte sahne planı.', icon: Sparkles },
  { id: 'lightshow', label: 'Işık Show', description: 'Işık şovu kuyruğu.', icon: Sun },
  { id: 'soundscape', label: 'Soundscape', description: 'Ortam ses manzarası.', icon: Music2 },
  { id: 'scentzone', label: 'Koku Zone', description: 'Koku / scent zone ayarları.', icon: Flower2 },
  { id: 'moodlight', label: 'Mood Light', description: 'Ruh hali aydınlatması.', icon: Lamp },
  { id: 'fogscene', label: 'Fog Scene', description: 'Sis / atmosfer efektleri.', icon: CloudFog },
  { id: 'projection', label: 'Projection', description: 'Projeksiyon mapping içerikleri.', icon: Projector },
  { id: 'immersive', label: 'Immersive', description: 'Immersive deneyim oturumları.', icon: Clapperboard },
  { id: 'hapticcue', label: 'Haptic Cue', description: 'Haptic / titreşim ipuçları.', icon: Activity },
  { id: 'atmosmix', label: 'Atmos Mix', description: 'Atmosfer karışım presetleri.', icon: Layers },
  { id: 'guestflow', label: 'Guest Flow', description: 'Deneyim alanı misafir akışı.', icon: Users },
  { id: 'scenectrl', label: 'Scene Control', description: 'Sahne kontrol snapshotları.', icon: SlidersHorizontal },
  { id: 'nightmode', label: 'Night Mode', description: 'Gece modu senaryoları.', icon: MoonStar },
  { id: 'dawnmode', label: 'Dawn Mode', description: 'Şafak modu senaryoları.', icon: Sunrise },
  { id: 'aurora', label: 'Aurora', description: 'AŞAMA 450 deneyim özeti.', icon: Sparkles },
  { id: 'harbor', label: 'Harbor', description: 'AŞAMA 435 liman özeti.', icon: Anchor },
  { id: 'tide', label: 'Tide', description: 'AŞAMA 420 sahil özeti.', icon: Waves },
  { id: 'odyssey', label: 'Odyssey', description: 'AŞAMA 405 finale özeti.', icon: Rocket },
  { id: 'zenith', label: 'Zenith', description: 'AŞAMA 390 gelir OS özeti.', icon: MountainSnow },
  { id: 'keystone', label: 'Keystone', description: 'AŞAMA 375 komuta kumaşı özeti.', icon: Landmark },
  { id: 'mirror', label: 'Mirror', description: 'AŞAMA 360 guest twin özeti.', icon: Sparkles },
  { id: 'lattice', label: 'Lattice', description: 'AŞAMA 345 edge mesh özeti.', icon: Radar },
  { id: 'vanguard', label: 'Vanguard', description: 'AŞAMA 330 Nexus Prime özeti.', icon: Rocket },
  { id: 'cognisphere', label: 'Cognisphere', description: 'AŞAMA 315 AI özeti.', icon: BrainCircuit },
  { id: 'brandpulse', label: 'Brand Pulse', description: 'AŞAMA 300 marka özeti.', icon: Sparkles },
  { id: 'ecosphere', label: 'Ecosphere', description: 'AŞAMA 285 ESG özeti.', icon: Leaf },
  { id: 'peoplehub', label: 'People Hub', description: 'AŞAMA 270 İK özeti.', icon: Users },
  { id: 'ledger', label: 'Ledger', description: 'AŞAMA 255 finans özeti.', icon: BookMarked },
  { id: 'meridian', label: 'Meridian', description: 'AŞAMA 240 oda servis özeti.', icon: Compass },
  { id: 'horizon', label: 'Horizon', description: 'AŞAMA 225 F&B/gelir özeti.', icon: Sunrise },
  { id: 'sentinel', label: 'Sentinel', description: 'AŞAMA 210 güvenlik özeti.', icon: ShieldAlert },
  { id: 'skyline', label: 'Skyline', description: 'AŞAMA 195 leisure özeti.', icon: Castle },
  { id: 'signalhub', label: 'Signal Hub', description: 'AŞAMA 180 altyapı özeti.', icon: SatelliteDish },
  { id: 'pyramid', label: 'Pyramid', description: 'AŞAMA 165 platform özeti.', icon: Pyramid },
  { id: 'apex', label: 'Apex', description: 'AŞAMA 150 zirve özeti.', icon: MountainSnow },
  { id: 'orbit', label: 'Orbit', description: 'AŞAMA 135 günlük yörünge.', icon: Orbit },
  { id: 'nightly', label: 'Night Audit', description: 'AŞAMA 120 gece kapanış.', icon: Telescope },
  { id: 'warroom', label: 'War Room', description: 'AŞAMA 105 komuta özeti.', icon: Radar },
  { id: 'boardpack', label: 'Board Pack', description: 'AŞAMA 90 yönetim paketi.', icon: BriefcaseBusiness },
  { id: 'digest', label: 'CEO Digest', description: 'AŞAMA 75 yönetici özeti.', icon: Newspaper },
  { id: 'readiness', label: 'Hazırlık Skoru', description: 'AŞAMA 60 panosu', icon: Gauge },
  { id: 'weather', label: 'Hava Brifi', description: 'Sahil operasyon', icon: CloudSun },
  { id: 'valet', label: 'Vale', description: 'Otopark fişleri', icon: Car },
  { id: 'music', label: 'Müzik', description: 'Playlist istekleri', icon: Music2 },
  { id: 'documents', label: 'Belgeler', description: 'Prosedür kasası', icon: FileText },
  { id: 'vendorscore', label: 'Tedarik Skor', description: 'Vendor scorecard', icon: Star },
  { id: 'waste', label: 'Fire', description: 'Atık günlüğü', icon: Trash2 },
  { id: 'seating', label: 'Oturma', description: 'Masa durumu', icon: Armchair },
  { id: 'waitlist', label: 'Bekleme', description: 'Misafir sırası', icon: ListOrdered },
  { id: 'complaints', label: 'Şikayetler', description: 'Escalation', icon: MessageCircleWarning },
  { id: 'kudos', label: 'Takdir', description: 'Kudos panosu', icon: Award },
  { id: 'hours', label: 'Saatler', description: 'Açılış/kapanış', icon: Clock3 },
  {
    id: 'training',
    label: 'Eğitim',
    description: 'SOCRATES quiz',
    icon: GraduationCap,
  },
  {
    id: 'audit',
    label: 'Denetim',
    description: 'Audit günlüğü',
    icon: ScrollText,
  },
  {
    id: 'webhooks',
    label: 'Webhooks',
    description: 'Outbound olay POST',
    icon: Webhook,
  },
  {
    id: 'docs',
    label: 'API Docs',
    description: 'OpenAPI uç noktaları',
    icon: BookOpen,
  },
  {
    id: 'settings',
    label: 'Platform Ayarları',
    description: 'API anahtarları & köprüler',
    icon: Settings,
  },
];

export default function Sidebar({
  active,
  allowedPages,
  userName,
  userRole,
  brands = [],
  activeBrandId,
  onBrandChange,
  onNavigate,
  onLogout,
}: SidebarProps) {
  const activeBrand = brands.find((b) => b.id === activeBrandId);
  const modules = new Set(activeBrand?.modules ?? []);

  const items = NAV_ITEMS.filter((item) => {
    if (!allowedPages.includes(item.id)) return false;
    if (!activeBrand || ALWAYS_VISIBLE.has(item.id)) return true;
    return modules.has(item.id);
  });

  return (
    <aside className="flex h-full w-72 shrink-0 flex-col border-r border-obsidian-700 bg-obsidian-900">
      <div className="flex items-center gap-3 border-b border-obsidian-700 px-5 py-5">
        <div className="glow-pulse flex size-11 items-center justify-center rounded-xl bg-lykia-500/15 text-lykia-400">
          <Mountain className="size-6" />
        </div>
        <div>
          <h1 className="text-sm font-bold tracking-wide text-lykia-300">OLYMPOSPASS</h1>
          <p className="text-xs text-slate-400">LİKYA CEO Paneli</p>
        </div>
      </div>

      {brands.length > 0 && (
        <div className="border-b border-obsidian-700 px-3 py-3">
          <label className="block">
            <span className="px-1 text-[10px] font-bold uppercase tracking-wider text-slate-500">
              Aktif marka
            </span>
            <select
              value={activeBrandId ?? ''}
              onChange={(e) => onBrandChange?.(e.target.value)}
              className="mt-1 w-full rounded-xl border border-obsidian-700 bg-obsidian-950 px-3 py-2 text-sm text-slate-100 focus:border-lykia-500 focus:outline-none"
            >
              {brands.map((b) => (
                <option key={b.id} value={b.id}>
                  {b.name}
                </option>
              ))}
            </select>
          </label>
        </div>
      )}

      <nav className="flex-1 space-y-1.5 overflow-y-auto p-3">
        {items.map(({ id, label, description, icon: Icon }) => {
          const isActive = active === id;
          return (
            <button
              key={id}
              type="button"
              onClick={() => onNavigate(id)}
              className={`group flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-left transition-colors ${
                isActive
                  ? 'bg-lykia-500/15 text-lykia-300'
                  : 'text-slate-300 hover:bg-obsidian-800 hover:text-slate-100'
              }`}
            >
              <Icon
                className={`size-5 shrink-0 ${isActive ? 'text-lykia-400' : 'text-slate-500 group-hover:text-slate-300'}`}
              />
              <span>
                <span className="block text-sm font-semibold">{label}</span>
                <span className="block text-xs text-slate-500">{description}</span>
              </span>
            </button>
          );
        })}
      </nav>

      <div className="border-t border-obsidian-700 p-4">
        <div className="mb-3 rounded-xl border border-obsidian-700 bg-obsidian-950/50 px-3 py-3">
          <p className="text-sm font-semibold text-slate-100">{userName}</p>
          <p className="mt-0.5 font-mono text-[11px] uppercase tracking-wider text-lykia-400/80">
            {userRole}
          </p>
        </div>
        <button
          type="button"
          onClick={onLogout}
          className="mb-3 flex w-full items-center justify-center gap-2 rounded-xl border border-obsidian-700 px-3 py-2 text-sm text-slate-300 transition hover:border-rose-500/40 hover:text-rose-300"
        >
          <LogOut className="size-4" />
          Çıkış Yap
        </button>
        <p className="text-[11px] leading-relaxed text-slate-500">
          Centilmenlik · Naiflik · Esprili Üslup
          <br />
          Antalya / Likya bölgesi operasyon merkezi
        </p>
      </div>
    </aside>
  );
}
